import type { ZodiacSign, PlanetName } from "./astro-utils";

export const PLANET_IN_SIGN: Record<string, string> = {
  "Güneş-Koç": "Cesur, lider ruhlu, girişimci. Kendini kanıtlama ihtiyacı ve güçlü bir irade.",
  "Güneş-Boğa": "Sabırlı, güvenilir, maddi güvenceye önem veren. Duyusal zevklere düşkün.",
  "Güneş-İkizler": "Meraklı, iletişimci, hızlı düşünen. Çok yönlü ama bazen yüzeysel.",
  "Güneş-Yengeç": "Duygusal, koruyucu, ailesine bağlı. Sezgileri güçlü, geçmişe özlem.",
  "Güneş-Aslan": "Gösterişli, yaratıcı, cömert. İlgi odağı olmayı sever, onurlu.",
  "Güneş-Başak": "Analitik, düzenli, detaycı. Hizmet etmeyi sever, mükemmeliyetçi.",
  "Güneş-Terazi": "Uyumlu, diplomatik, adaletli. İlişkilerde denge arar, estetik duyarlılığı yüksek.",
  "Güneş-Akrep": "Tutkulu, gizemli, dönüştürücü. Derin duygular, güçlü sezgi.",
  "Güneş-Yay": "İyimser, maceracı, felsefi. Özgürlüğüne düşkün, bilgelik arayışında.",
  "Güneş-Oğlak": "Hırslı, disiplinli, sorumluluk sahibi. Uzun vadeli hedeflere odaklı.",
  "Güneş-Kova": "Özgün, yenilikçi, bağımsız. Toplumsal konulara duyarlı, sıra dışı.",
  "Güneş-Balık": "Merhametli, sezgisel, hayalperest. Sanatsal yetenekler, sınırların erimesi.",

  "Ay-Koç": "Duyguları ani ve yoğun. İçgüdüsel tepkiler verir, sabırsız.",
  "Ay-Boğa": "Duygusal olarak istikrarlı, güvenceye ihtiyaç duyar. Konfora düşkün.",
  "Ay-İkizler": "Duyguları değişken, zihinsel uyarılmaya ihtiyaç duyar. Meraklı.",
  "Ay-Yengeç": "Duygusal ve sezgisel. Güçlü annelik içgüdüsü, geçmişe bağlı.",
  "Ay-Aslan": "Duygularını gururla ifade eder. İlgi ve takdir görmek ister.",
  "Ay-Başak": "Duygularını analiz eder. Yardımsever ama eleştirel olabilir.",
  "Ay-Terazi": "Duygusal uyum arar. İlişkilerde barışçıl, çatışmadan kaçınır.",
  "Ay-Akrep": "Duyguları yoğun ve derin. Sahiplenici, gizemli, dönüştürücü.",
  "Ay-Yay": "Duygusal olarak özgür ruhlu. İyimser, maceracı, bağımsız.",
  "Ay-Oğlak": "Duygularını kontrol eder, mesafeli durabilir. Sorumluluk sahibi.",
  "Ay-Kova": "Duygusal olarak bağımsız, özgün tepkiler verir. Toplumsal duyarlılık.",
  "Ay-Balık": "Son derece hassas ve sezgisel. Sınırları belirsiz, şefkatli.",

  "Merkür-Koç": "Hızlı düşünür, acele konuşur. Zihni keskin ve doğrudan.",
  "Merkür-Boğa": "Pratik düşünür, yavaş ama sağlam kararlar alır.",
  "Merkür-İkizler": "Zihni sürekli aktif. İletişim yeteneği yüksek, öğrenmeye açık.",
  "Merkür-Yengeç": "Hafızası güçlü, sezgisel düşünür. Duygusal iletişim kurar.",
  "Merkür-Aslan": "Yaratıcı ve etkileyici konuşur. Fikirlerini gururla savunur.",
  "Merkür-Başak": "Analitik zihin, detaycı. Mükemmel iletişimci ve eleştirmen.",
  "Merkür-Terazi": "Diplomatik, uyumlu iletişim. Karar vermekte zorlanabilir.",
  "Merkür-Akrep": "Derinlemesine araştıran, gizemli. Sert ve keskin konuşabilir.",
  "Merkür-Yay": "Geniş perspektif, felsefi düşünce. Açık sözlü ve iyimser.",
  "Merkür-Oğlak": "Disiplinli düşünce, pratik zihin. Ciddi ve planlı iletişim.",
  "Merkür-Kova": "Özgün fikirler, ilerici düşünce. Alışılmışın dışında bakar.",
  "Merkür-Balık": "Sezgisel düşünce, hayal gücü geniş. Sanatsal ve yaratıcı iletişim.",

  "Venüs-Koç": "Aşkta atılgan, tutkulu. Hızlı âşık olur, rekabetçidir.",
  "Venüs-Boğa": "Aşkta sadık, duyusal. Güvence ve rahatlık arar.",
  "Venüs-İkizler": "Aşkta meraklı, flörtöz. Zihinsel uyum önemlidir.",
  "Venüs-Yengeç": "Sevgi dolu, koruyucu. Duygusal bağ ve güven arar.",
  "Venüs-Aslan": "Romantik, cömert. Büyük jestlerle sever, gösterişli.",
  "Venüs-Başak": "Sevgisini hizmetle gösterir. Mütevazı ve detaycı.",
  "Venüs-Terazi": "Romantik ve uyumlu. İlişkilerde denge ve güzellik arar.",
  "Venüs-Akrep": "Tutkulu, sahiplenici. Derin ve dönüştürücü ilişkiler.",
  "Venüs-Yay": "Aşkta özgür ruhlu, maceracı. Bağımsız ve iyimser.",
  "Venüs-Oğlak": "Sevgisini sorumlulukla gösterir. Ciddi ve istikrarlı ilişkiler.",
  "Venüs-Kova": "Aşkta özgün, arkadaşça. Alışılmadık ilişki biçimlerine açık.",
  "Venüs-Balık": "Koşulsuz seven, fedakâr. Romantik ve hayalperest.",

  "Mars-Koç": "Enerjisi yüksek, cesur. Doğrudan harekete geçer, rekabetçi.",
  "Mars-Boğa": "Kararlı, inatçı. Enerjisini sabırla kullanır, güçlü irade.",
  "Mars-İkizler": "Zihinsel enerji yüksek. Aynı anda birçok işle ilgilenir.",
  "Mars-Yengeç": "Duygusal tepkiler. Koruyucu içgüdü, pasif-agresif olabilir.",
  "Mars-Aslan": "Yaratıcı enerji, liderlik. Gururu incindiğinde öfkelenebilir.",
  "Mars-Başak": "Pratik ve verimli çalışır. Detaylara takılabilir.",
  "Mars-Terazi": "Uyumlu çaba, diplomasi. Çatışmadan kaçınır, uzlaşmacı.",
  "Mars-Akrep": "Yoğun tutku, güçlü irade. Savaşçı, stratejik.",
  "Mars-Yay": "Maceraperest, enerjik. Doğrudan ve açık sözlü.",
  "Mars-Oğlak": "Disiplinli hırs, planlı hareket. Uzun vadeli hedefler için çalışır.",
  "Mars-Kova": "Bağımsız hareket, özgün yöntemler. Toplumsal dava için enerji.",
  "Mars-Balık": "Dolaylı hareket, sezgisel. Enerjisini sanata veya maneviyata yönlendirebilir.",
};

export const PLANET_IN_HOUSE: Record<string, string> = {
  "Güneş-1": "Kişilik, kendini ifade ve fiziksel görünüm üzerinde güçlü etki. Liderlik doğal.",
  "Güneş-2": "Maddi değerler, gelir ve benlik saygısı konularında odak. Para kazanma yeteneği.",
  "Güneş-3": "İletişim, öğrenme ve yakın çevre ile ilişkiler. Zihinsel olarak aktif.",
  "Güneş-4": "Aile, kökler ve ev hayatı önemli. Duygusal güvenlik arayışı.",
  "Güneş-5": "Yaratıcılık, romantizm ve çocuklarla ilgili konular. Sanatsal yetenek.",
  "Güneş-6": "İş, sağlık ve günlük rutinler. Hizmet etme arzusu ve detaylara özen.",
  "Güneş-7": "İlişkiler, ortaklıklar ve evlilik. Dengeli ve uyumlu bağlantılar kurma.",
  "Güneş-8": "Derin dönüşüm, miras ve gizemli konular. Güçlü sezgiler ve araştırma.",
  "Güneş-9": "Yüksek öğrenim, seyahat ve felsefe. Bilgelik arayışı ve geniş perspektif.",
  "Güneş-10": "Kariyer, toplumsal statü ve başarı. Hırslı ve hedef odaklı.",
  "Güneş-11": "Arkadaşlıklar, sosyal çevre ve idealler. Grup çalışması ve vizyon.",
  "Güneş-12": "Bilinçaltı, yalnızlık ve maneviyat. İçsel çalışma ve gizli yetenekler.",

  "Ay-1": "Duygusal ifade açık, ruh hali dışa dönük. Sezgileri kuvvetli ve değişken.",
  "Ay-2": "Duygusal güvence maddi değerlerle bağlantılı. Harcama alışkanlıkları değişken.",
  "Ay-3": "Duygusal iletişim güçlü, aile üyeleriyle yakın bağ. Meraklı bir zihin.",
  "Ay-4": "Aile ve ev hayatı duygusal merkez. Güçlü annelik içgüdüsü.",
  "Ay-5": "Yaratıcılık duygusal bir çıkış. Çocuklarla ve hobilerle duygusal bağ.",
  "Ay-6": "Duygusal sağlık hassasiyeti. İş ortamında besleyici rol üstlenme.",
  "Ay-7": "Duygusal ortaklık ihtiyacı. Partnerle duygusal bağ kurma isteği.",
  "Ay-8": "Derin duygusal bağlar, dönüşüm. Sezgisel olarak güçlü, tutkulu.",
  "Ay-9": "Duygusal olarak maceracı. Seyahat ve keşif ruhu besler.",
  "Ay-10": "Duygusal kariyer bağlantısı. İş hayatında besleyici figür olma eğilimi.",
  "Ay-11": "Arkadaş gruplarıyla duygusal bağ. İdealler ve toplumsal konulara duyarlılık.",
  "Ay-12": "Bilinçaltı duygular güçlü. Yalnızlık ve meditasyonla duygusal denge.",

  "Merkür-1": "Zihinsel olarak aktif, konuşkan. Meraklı ve hızlı öğrenen bir kişilik.",
  "Merkür-2": "Zihinsel çaba maddi kazanca yönelik. Pratik düşünce ve planlama.",
  "Merkür-3": "Doğal iletişimci. Kardeşler ve yakın çevreyle güçlü bağ.",
  "Merkür-4": "Aile geçmişine ilgi. Erken çocukluk anıları canlı.",
  "Merkür-5": "Yaratıcı düşünce, zekice espriler. Hobilerde ve oyunlarda stratejik.",
  "Merkür-6": "Detaycı ve analitik zihin. İş ve sağlık konularında pratik çözümler.",
  "Merkür-7": "İlişkilerde iletişim önemli. Zihinsel uyum aranan bir partner.",
  "Merkür-8": "Derin düşünce, araştırmacı zihin. Gizemli konulara ilgi.",
  "Merkür-9": "Felsefi düşünce, yüksek öğrenime ilgi. Farklı kültürlere merak.",
  "Merkür-10": "Profesyonel iletişim, zihinsel başarı. Kariyer odaklı düşünce.",
  "Merkür-11": "Sosyal çevrede fikir alışverişi. Arkadaşlarla zihinsel uyum.",
  "Merkür-12": "Bilinçaltı düşünce modelleri. Psikoloji ve maneviyata ilgi.",

  "Venüs-1": "Çekici kişilik, doğal cazibe. İlişkilerde sıcak ve sevecen.",
  "Venüs-2": "Maddi rahatlık ve güzellik zevki. Lüks ve konfora düşkün.",
  "Venüs-3": "Tatlı dil, sosyal iletişim. Sanatsal zeka ve estetik duyarlılık.",
  "Venüs-4": "Evde uyum ve huzur arar. Aile ile güçlü sevgi bağları.",
  "Venüs-5": "Yaratıcı ve sanatsal yetenekler. Romantik ve eğlenceli.",
  "Venüs-6": "İş ortamında uyum sever. Güzelliği günlük rutine dahil eder.",
  "Venüs-7": "İlişkilere odaklı, evliliğe yatkın. Uzlaşmacı ve sevgi dolu.",
  "Venüs-8": "Derin duygusal bağlar, tutkulu aşk. Dönüştürücü ilişkiler.",
  "Venüs-9": "Uzak kültürlere ve sanata ilgi. Romantik seyahat ve macera.",
  "Venüs-10": "Sosyal başarı, popülerlik. İş hayatında zarafet ve diplomasi.",
  "Venüs-11": "Arkadaşlarla sevgi dolu bağlar. Sosyal çevrede popüler.",
  "Venüs-12": "Gizli sevgiler, özverili aşk. Sanatsal yetenekler bilinçaltından gelir.",

  "Mars-1": "Enerjik, girişimci, cesur. Doğal lider ve rekabetçi.",
  "Mars-2": "Para kazanmak için enerjik çaba. Maddi hedefler için savaşır.",
  "Mars-3": "Zihinsel enerji yüksek. Tartışmacı ve fikirlerini savunur.",
  "Mars-4": "Evde gerginlik olabilir. Aile içinde liderlik mücadelesi.",
  "Mars-5": "Yaratıcı enerji, spor ve rekabet. Romantik olarak atılgan.",
  "Mars-6": "Detaylara enerji harcar. İş hayatında yoğun çaba.",
  "Mars-7": "İlişkilerde rekabet veya tutku. Güçlü iradeli partner.",
  "Mars-8": "Derin tutkular ve dönüşüm. Psikolojik güç ve strateji.",
  "Mars-9": "Macera ve seyahat isteği. Fikirleri tutkuyla savunur.",
  "Mars-10": "Hırslı, başarı odaklı. Profesyonel hayatta güçlü ve kararlı.",
  "Mars-11": "Toplumsal konularda aktif. Arkadaşlarla rekabet veya spor.",
  "Mars-12": "Gizli enerji, bastırılmış öfke. Egzersiz ve yalnızlıkla dengelenir.",
};

export const ASPECT_MEANINGS: Record<string, string> = {
  "Kavuşum": "Gezegenlerin enerjisi birleşir. Güçlü bir odak noktası, o konuda yoğunlaşma. Türüne göre olumlu veya nötr.",
  "Altmışlık": "Destekleyici ve uyumlu akış. Gezegenler arasında doğal bir işbirliği, kolaylıkla ifade edilen yetenekler.",
  "Kare": "Gerginlik ve mücadele. Bu enerjiyi dengelemek için çaba gerekir. Büyüme ve gelişmeyi tetikler.",
  "Üçgen": "Doğal yetenek ve uyum. Gezegenler arasında kolay bir enerji akışı. Yeteneklerin rahatça ifadesi.",
  "Karşıt": "Denge arayışı. İki enerji arasında gerilim ama tamamlayıcılık. Dışarıya yansıtılan ve içselleştirilen arasındaki denge.",
};

export const HOUSE_MEANINGS: Record<number, { title: string; meaning: string }> = {
  1: { title: "1. Ev (Yükselen)", meaning: "Kişiliğiniz, fiziksel görünümünüz, dış dünyaya gösterdiğiniz maske. Doğal davranış biçiminiz ve hayata yaklaşımınız." },
  2: { title: "2. Ev", meaning: "Maddi değerler, gelir, yetenekler ve benlik saygısı. Paranızı nasıl kazandığınız ve harcadığınız." },
  3: { title: "3. Ev", meaning: "İletişim, öğrenme biçimi, kardeşler ve yakın çevre. Günlük iletişim tarzınız ve merak duygunuz." },
  4: { title: "4. Ev (IC)", meaning: "Aile kökleri, ev hayatı, çocukluk anıları. İç dünyanız ve duygusal güvenliğiniz." },
  5: { title: "5. Ev", meaning: "Yaratıcılık, romantizm, hobiler ve çocuklar. Hayattan zevk alış biçiminiz ve eğlence tarzınız." },
  6: { title: "6. Ev", meaning: "Günlük rutinler, iş hayatı, sağlık ve hizmet. Beden sağlığınız ve çalışma alışkanlıklarınız." },
  7: { title: "7. Ev (Alçalan)", meaning: "İkili ilişkiler, ortaklıklar, evlilik. Karşınızdakini nasıl gördüğünüz ve denge arayışınız." },
  8: { title: "8. Ev", meaning: "Derin dönüşüm, miras, ölüm ve yeniden doğuş. Psikolojik derinlik, gizli konular ve başkalarının kaynakları." },
  9: { title: "9. Ev", meaning: "Yüksek öğrenim, seyahat, felsefe, inançlar. Hayatı anlama arayışınız ve bilgelik." },
  10: { title: "10. Ev (MC)", meaning: "Kariyer, toplumsal konum, başarı. Dünyaya bırakmak istediğiniz iz ve mesleki hedefleriniz." },
  11: { title: "11. Ev", meaning: "Arkadaşlıklar, sosyal çevre, idealler. Umutlarınız, hayalleriniz ve toplumsal bağlantılarınız." },
  12: { title: "12. Ev", meaning: "Bilinçaltı, yalnızlık, maneviyat. Gizli düşmanlar, karmanız ve ruhsal yolculuğunuz." },
};

export const RISING_SIGNS: Record<ZodiacSign, string> = {
  "Koç": "Koç yükselenler cesur, girişimci ve doğrudan bir kişilik sergiler. Fiziksel olarak atletik ve enerjik görünebilirler. Hayata 'ben' bilinciyle yaklaşır, öncü olmayı severler.",
  "Boğa": "Boğa yükselenler sakin, güvenilir ve sabırlı bir izlenim bırakır. Sağlam bir vücut yapısına sahip olabilirler. Hayata 'sahip olma' bilinciyle yaklaşır, istikrar ararlar.",
  "İkizler": "İkizler yükselenler meraklı, konuşkan ve genç görünümlüdür. Sosyal ortamlarda rahat eder, sürekli bilgi paylaşırlar. Hayata 'düşünme' bilinciyle yaklaşırlar.",
  "Yengeç": "Yengeç yükselenler yumuşak, duygusal ve koruyucu bir dış görünüş sergiler. Yuvarlak yüz hatları olabilir. Hayata 'hissetme' bilinciyle yaklaşır, güvenlik ararlar.",
  "Aslan": "Aslan yükselenler gururlu, cömert ve etkileyici bir duruş sergiler. Dikkat çekici bir fiziksel görünümleri vardır. Hayata 'ben yapacağım' bilinciyle yaklaşırlar.",
  "Başak": "Başak yükselenler mütevazı, analitik ve detaycı görünür. Düzenli ve temiz bir fiziksel görünümleri vardır. Hayata 'hizmet' bilinciyle yaklaşırlar.",
  "Terazi": "Terazi yükselenler zarif, uyumlu ve sosyal bir izlenim bırakır. Çekici ve dengeli yüz hatları olabilir. Hayata 'denge' bilinciyle yaklaşır, ilişkilere odaklanır.",
  "Akrep": "Akrep yükselenler gizemli, yoğun ve etkileyici bir duruş sergiler. Keskin bakışları ve güçlü bir varlıkları vardır. Hayata 'dönüşüm' bilinciyle yaklaşırlar.",
  "Yay": "Yay yükselenler iyimser, maceracı ve açık sözlü görünür. Atletik ve hareketli bir yapıları olabilir. Hayata 'keşif' bilinciyle yaklaşır, özgürlük ararlar.",
  "Oğlak": "Oğlak yükselenler ciddi, disiplinli ve olgun görünür. Sorumlu bir duruş sergiler, yaşlandıkça gençleşirler. Hayata 'başarı' bilinciyle yaklaşırlar.",
  "Kova": "Kova yükselenler özgün, bağımsız ve sıra dışı bir görünüm sergiler. Toplumsal konulara duyarlı, arkadaş canlısıdır. Hayata 'farkındalık' bilinciyle yaklaşırlar.",
  "Balık": "Balık yükselenler yumuşak, sezgisel ve hayalperest bir izlenim bırakır. Rüya gibi bir ifadeleri vardır. Hayata 'bağlantı' bilinciyle yaklaşır, sanatsal ve duygusaldır.",
};

export const BODY_SYMBOL: Record<PlanetName, string> = {
  "Güneş": "☉",
  "Ay": "☽",
  "Merkür": "☿",
  "Venüs": "♀",
  "Mars": "♂",
  "Jüpiter": "♃",
  "Satürn": "♄",
  "Uranüs": "♅",
  "Neptün": "♆",
  "Plüton": "♇",
  "Yükselen": "☊",
};

export const BODY_RULERSHIPS: Record<PlanetName, string> = {
  "Güneş": "Öz bilinç, irade, canlılık, ego. Ne olduğunuz, kimlik ve yaşam amacı.",
  "Ay": "Duygular, sezgiler, alışkanlıklar, bilinçaltı. Nasıl hissettiğiniz ve duygusal ihtiyaçlar.",
  "Merkür": "Zihin, iletişim, öğrenme, mantık. Nasıl düşündüğünüz ve ifade ettiğiniz.",
  "Venüs": "Sevgi, güzellik, para, ilişkiler, sanat. Neyi sevdiğiniz ve değer verdiğiniz.",
  "Mars": "Enerji, tutku, cesaret, savaşma arzusu. Nasıl harekete geçtiğiniz ve istediğinizi nasıl aldığınız.",
  "Jüpiter": "Bolluk, genişleme, bilgelik, şans. Hayatta nerede büyüdüğünüz ve fırsat bulduğunuz.",
  "Satürn": "Disiplin, sorumluluk, sınırlar, kaygılar. Hayat dersleriniz, olgunlaşma ve sınanma alanlarınız.",
  "Uranüs": "Değişim, özgünlük, isyan, yenilik. Sıra dışı yanınız ve özgürleşme ihtiyacınız.",
  "Neptün": "Hayaller, sezgiler, yanılsamalar, ruhsallık. Manevi yönünüz ve ilham kaynağınız.",
  "Plüton": "Dönüşüm, güç, derinlik, yok etme ve yeniden doğuş. En derin dönüşüm ve güç alanınız.",
  "Yükselen": "Dış görünüş, hayata yaklaşım. Başkalarının sizi ilk gördüğünde algıladığı kişilik maskesi.",
};

export function getPlanetInSignText(planet: PlanetName, sign: ZodiacSign): string {
  return PLANET_IN_SIGN[`${planet}-${sign}`] || "";
}

export function getPlanetInHouseText(planet: PlanetName, house: number): string {
  return PLANET_IN_HOUSE[`${planet}-${house}`] || "";
}
