export interface FunTestOption {
  text: string;
  score: number;
}

export interface FunTestQuestion {
  text: string;
  options: FunTestOption[];
}

export interface FunTestResult {
  title: string;
  description: string;
  advice: string;
  scoreRange: [number, number];
}

export interface FunTest {
  id: string;
  title: string;
  description: string;
  icon: string;
  questions: FunTestQuestion[];
  results: FunTestResult[];
  maxScore: number;
}

function t(text: string, options: [string, number][]): FunTestQuestion {
  return {
    text,
    options: options.map(([text, score]) => ({ text, score })),
  };
}

export const FUN_TESTS: FunTest[] = [
  {
    id: "sinir-seviyesi",
    title: "Ne Kadar Sinirlisin?",
    description: "İçindeki volkanı keşfet! Günlük olaylar karşısında ne kadar öfkeli olduğunu bu testle ölç.",
    icon: "🌋",
    questions: [
      t("Bir kafede siparişin yanlış geldiğinde ne yaparsın?", [
        ["Gülümser ve kibarca düzeltilmesini isterim", 1],
        ["Derin bir nefes alır, yine de garsona çıkışmam", 2],
        ["Kaşlarımı çatıp sesimi yükseltirim", 3],
        ["Müdürü çağırıp şikayet ederim", 4],
      ]),
      t("Trafikte sıkışıp kaldığında nasıl hissedersin?", [
        ["Radyo açar, keyfime bakarım", 1],
        ["Hafif gergin olurum ama sakin kalırım", 2],
        ["Sürekli korna çalarım", 3],
        ["Arabanın içinde bağırıp direksiyona yumruk atarım", 4],
      ]),
      t("Biri sırada önüne geçmeye çalıştığında tepkin ne olur?", [
        ["Bir şey demem, belki acelesi vardır", 1],
        ["Kibarca sırada benim olduğumu söylerim", 2],
        ["Yüksek sesle uyarırım", 3],
        ["Önüne geçip ittiririm", 4],
      ]),
      t("Arkadaşın planlanan buluşmaya 1 saat geç kaldığında ne yaparsın?", [
        ["Merak ederim, başına bir şey gelmediğine sevinirim", 1],
        ["Hafif kırılırım ama anlayışlı davranırım", 2],
        ["Soğuk davranırım, trip atarım", 3],
        ["O gelmeden giderim", 4],
      ]),
      t("Teknoloji cihazın donduğunda tepkin ne olur?", [
        ["Sakin sakin yeniden başlatırım", 1],
        ["Bir iki kere dener, sonra bırakırım", 2],
        ["Cihaza küfrederim", 3],
        ["Cihazı duvara fırlatırım", 4],
      ]),
      t("Tartışma sırasında ses tonun nasıldır?", [
        ["Her zaman sakin ve kontrollü", 1],
        ["Bazen yükselir ama toparlarım", 2],
        ["Sık sık bağırmaya başlarım", 3],
        ["Kontrolümü tamamen kaybederim", 4],
      ]),
      t("Bir işi yaparken sürekli hata yaptığında ne hissedersin?", [
        ["Hatalar öğrenme fırsatıdır diye düşünürüm", 1],
        ["Biraz sinirlenir ama devam ederim", 2],
        ["Sinirden ne yaptığımı bilmem", 3],
        ["Eşyaları fırlatıp vazgeçerim", 4],
      ]),
      t("Biri sana kaba bir yorum yaptığında nasıl tepki verirsin?", [
        ["Takmam, güler geçerim", 1],
        ["Kibarca cevap veririm", 2],
        ["Aynı şekilde karşılık veririm", 3],
        ["Fiziksel müdahalede bulunurum", 4],
      ]),
      t("Oyun oynarken kaybettiğinde ne yaparsın?", [
        ["Tebrik eder, bir sonraki oyuna odaklanırım", 1],
        ["Hafif bozulurum ama belli etmem", 2],
        ["Küser veya oyunu terk ederim", 3],
        ["Kumandayı fırlatırım", 4],
      ]),
      t("Beklemediğin bir anda gelen kötü haber nasıl bir tepki yaratır?", [
        ["Sakin karşılar, çözüm ararım", 1],
        ["Üzülür ama hemen toparlanırım", 2],
        ["Bağırarak tepki veririm", 3],
        ["Kontrolümü kaybeder, etrafa zarar veririm", 4],
      ]),
      t("Telefon görüşmesinde beklemeye alındığında ne hissedersin?", [
        ["Sesli mesaj bırakır, geri ararım", 1],
        ["Bir süre bekler, sonra kapatırım", 2],
        ["Görevliye çıkışırım", 3],
        ["Telefonu duvara fırlatırım", 4],
      ]),
      t("Çok sevdiğin bir yemek döküldüğünde ne yaparsın?", [
        ["Sorun değil, yeniden hazırlarım derim", 1],
        ["Hay allah deyip temizlerim", 2],
        ["Sinirle bağırırım", 3],
        ["Tabağı da duvara fırlatırım", 4],
      ]),
      t("İnternet bağlantın sürekli koptuğunda ne yaparsın?", [
        ["Sakin bir şekilde modemi resetlerim", 1],
        ["Yetkiliyi ararım", 2],
        ["Modeme bağırır, tehdit ederim", 3],
        ["Modemi pencereden atarım", 4],
      ]),
      t("Bir arkadaşın sırrını başkasına anlattığını öğrendiğinde ne yaparsın?", [
        ["Konuşur, nedenini anlamaya çalışırım", 1],
        ["Kırılırım ama affederim", 2],
        ["Hemen yüzleşir ve suçlarım", 3],
        ["0 an itibarıyla o kişi benim için biter", 4],
      ]),
      t("Favori takımın önemli bir maçı kaybettiğinde tepkin ne olur?", [
        ["Üzülürüm ama hayat devam eder", 1],
        ["Keyfim kaçar bir süre", 2],
        ["TV'ye bağırır, küfrederim", 3],
        ["Eşyaları tekmelemeye başlarım", 4],
      ]),
      t("Bir iş için uzun süre beklemen gerektiğinde nasıl davranırsın?", [
        ["Kitap okur, müzik dinlerim", 1],
        ["Sıkılırım ama sabrederim", 2],
        ["Sürekli yetkiliye baskı yaparım", 3],
        ["Gürültü çıkarır, şikayet ederim", 4],
      ]),
      t("Biri sana defalarca aynı soruyu sorduğunda tepkin ne olur?", [
        ["Her seferinde sabırla cevaplarım", 1],
        ["Biraz sıkılsam da cevaplarım", 2],
        ["'Ben söyledim ya!' diye çıkışırım", 3],
        ["Hiç cevap vermem, uzaklaşırım", 4],
      ]),
      t("Birisinin sana haksızlık yaptığını düşündüğünde ne yaparsın?", [
        ["Medeni bir şekilde konuşurum", 1],
        ["Durumu anlatmaya çalışırım", 2],
        ["Hemen savunmaya geçer, bağırırım", 3],
        ["Şiddet içeren tepkiler veririm", 4],
      ]),
      t("Uykusuz kaldığında günlük olaylara tepkin nasıl olur?", [
        ["Yine de sakin kalmayı başarırım", 1],
        ["Normalden daha gergin olurum", 2],
        ["En ufak şeyde patlarım", 3],
        ["Her şeye saldırgan tepki veririm", 4],
      ]),
      t("Kalabalık bir yerde biri sana çarpıp özür dilemediğinde ne yaparsın?", [
        ["Takmam, yoluma devam ederim", 1],
        ["Arkamdan homurdanırım", 2],
        ["'Dikkat et' diye seslenirim", 3],
        ["Arkadaşının önünü keser, hesap sorarım", 4],
      ]),
    ],
    results: [
      {
        title: "Sakin Melek",
        description: "Neredeyse hiçbir şey seni sinirlendirmiyor! Olimpos Dağı'nın zirvesinde bir bilge gibi, olayların üstünde kalabiliyorsun. Çevrendekiler senin bu sakinliğine hayran kalıyor. Sen bir huzur adasısın.",
        advice: "Bu sakinliğini koru, ama bazen duygularını da ifade etmekten çekinme. Her şeyi içine atmamak da önemli.",
        scoreRange: [20, 35],
      },
      {
        title: "Dengeli Kan",
        description: "Normal insan tepkileri veriyorsun. Kimi zaman sinirleniyor, kimi zaman sakin kalabiliyorsun. Bu denge sayesinde çevrendekiler seni anlayışlı biri olarak tanıyor.",
        advice: "Sağlıklı bir dengedesin. Stres anlarında nefes egzersizleri yapmayı dene, mevcut dengeni koru.",
        scoreRange: [36, 50],
      },
      {
        title: "Ateş Topu",
        description: "İçinde bir volkan var ve sık sık patlamaya hazır bekliyor! Küçük olaylar bile seni harekete geçirebiliyor. Öfkeni kontrol etmekte zorlanıyorsun ve bu bazen pişmanlık duymana neden oluyor.",
        advice: "Öfke kontrolü üzerine çalışman iyi olabilir. Derin nefes, spor ve meditasyon sana iyi gelecektir.",
        scoreRange: [51, 65],
      },
      {
        title: "Volkan Patlaması",
        description: "Dikkat! Sen tam bir öfke kontrolü vakasısın. En ufak bir kıvılcımda patlamaya hazır bir yanardağ gibi yaşıyorsun. Bu durum hem sana hem çevrendekilere zarar veriyor. Kontrolü kaybetmek yerine kontrol altına almayı öğrenmelisin.",
        advice: "Profesyonel yardım almayı düşünmelisin. Öfkenin altında yatan nedenleri keşfetmek ve başa çıkma stratejileri geliştirmek hayat kaliteni artıracaktır.",
        scoreRange: [66, 80],
      },
    ],
  },
  {
    id: "iliski-olgunlugu",
    title: "İlişki Olgunluğun",
    description: "Bir ilişkide ne kadar olgun davranıyorsun? Partnerine karşı anlayış ve sorumluluk seviyeni ölç.",
    icon: "💑",
    questions: [
      t("Partnerin seni üzdüğünde ilk tepkin ne olur?", [
        ["Konuşarak çözmeye çalışırım", 1],
        ["Biraz mesafe koyup düşünürüm", 2],
        ["Hemen suçlayıcı konuşurum", 3],
        ["Trip atarım, konuşmam", 4],
      ]),
      t("Partnerinin senden farklı fikirleri olduğunda ne yaparsın?", [
        ["Saygı duyar, tartışırım", 1],
        ["Dinlerim ama ikna etmeye çalışırım", 2],
        ["Kendi fikrimin doğru olduğunda ısrar ederim", 3],
        ["Kavga çıkarırım", 4],
      ]),
      t("Partnerinin geçmiş ilişkileri hakkında ne düşünürsün?", [
        ["Geçmiş geçmiştir, önemli değil", 1],
        ["Bazen merak ederim ama sormam", 2],
        ["Sürekli sorgularım", 3],
        ["Kıskançlık krizlerine girerim", 4],
      ]),
      t("Partnerin başarılı olduğunda nasıl hissedersin?", [
        ["İçtenlikle mutlu olur, kutlarım", 1],
        ["Gurur duyarım ama biraz kıskanırım", 2],
        ["Kendimi yetersiz hissederim", 3],
        ["Görmezden gelirim", 4],
      ]),
      t("Bir tartışma sırasında nasıl davranırsın?", [
        ["Sakin kalır, çözüm odaklı konuşurum", 1],
        ["Bazen sesimi yükseltsem de toparlarım", 2],
        ["Bağırmaya başlarım", 3],
        ["Küfür eder veya hakaret ederim", 4],
      ]),
      t("Partnerinin arkadaşlarıyla vakit geçirmesine nasıl bakarsın?", [
        ["Desteklerim, birlikte vakit geçirmekten mutlu olurum", 1],
        ["Kendi halinde takılmasına izin veririm", 2],
        ["Kıskanırım, sürekli mesaj atarım", 3],
        ["Yasaklamaya çalışırım", 4],
      ]),
      t("Partnerin zor bir gün geçirdiğinde ne yaparsın?", [
        ["Dinler, destek olur, yanında olurum", 1],
        ["Nasıl yardım edebilirim diye sorarım", 2],
        ["Kendi sorunlarımı anlatmaya başlarım", 3],
        ["İlgilenmem, kendi işime bakarım", 4],
      ]),
      t("Küçük bir anlaşmazlıkta özür diler misin?", [
        ["Hatanı görür görmez özür dilerim", 1],
        ["Bazen özür dilerim, bazen beklerim", 2],
        ["Çok zor özür dilerim", 3],
        ["Asla özür dilemem, beklerim", 4],
      ]),
      t("Partnerinin özel alanına ne kadar saygı duyarsın?", [
        ["Tamamen saygı duyarım, güven önemlidir", 1],
        ["Bazen sınırları zorlasam da genelde saygılıyım", 2],
        ["Sürekli telefonunu kontrol etmek isterim", 3],
        ["Her anını takip ederim", 4],
      ]),
      t("Bir sorun olduğunda çözüm için ne yaparsın?", [
        ["Oturur konuşur, ortak çözüm bulurum", 1],
        ["Önce sakinleşir sonra konuşurum", 2],
        ["Sorunu görmezden gelirim", 3],
        ["Hemen ilişkiyi bitirmekle tehdit ederim", 4],
      ]),
      t("Partnerinin hobilerine nasıl yaklaşırsın?", [
        ["Destekler, hatta bazen katılırım", 1],
        ["Saygı duyar, kendi hobi zamanını veririm", 2],
        ["Beni ihmal ettiğini düşünürüm", 3],
        ["Hobilerini küçümser, engellemeye çalışırım", 4],
      ]),
      t("İlişkide kararlar nasıl alınmalı sence?", [
        ["Ortak kararlar alınmalı, herkesin fikri alınmalı", 1],
        ["Dönüşümlü olarak karar verilmeli", 2],
        ["Benim dediğim olmalı", 3],
        ["Kim güçlüyse o karar verir", 4],
      ]),
      t("Partnerin bir hata yaptığında nasıl tepki verirsin?", [
        ["Hatalar olabilir, destek olurum", 1],
        ["Hatayı belirtir ama affederim", 2],
        ["Sürekli hatayı yüzüne vururum", 3],
        ["Küçümser ve aşağılarım", 4],
      ]),
      t("İlişkideki sorumluluklarını nasıl yerine getirirsin?", [
        ["Üzerime düşeni fazlasıyla yaparım", 1],
        ["Paylaşarak yürütürüz", 2],
        ["Biraz ihmalkar davranırım", 3],
        ["Tüm yük partnerimde olmalı, derim", 4],
      ]),
      t("Eski sevgilinle nasıl bir ilişkin var?", [
        ["Tamamen kapattım, iletişimim yok", 1],
        ["Ara sıra selamlaşırız", 2],
        ["Gizlice görüşürüm", 3],
        ["Hâlâ duygularım var", 4],
      ]),
      t("Partnerine sürpriz yapmayı sever misin?", [
        ["Sık sık sürpriz yapar, mutlu ederim", 1],
        ["Özel günlerde yaparım", 2],
        ["Aklıma gelmez pek", 3],
        ["Uğraşmam, gerekli mi?", 4],
      ]),
      t("Partnerin ailesiyle nasıl geçinirsin?", [
        ["Çok iyi anlaşırız, seviyorum onları", 1],
        ["İdare eder, saygılı davranırım", 2],
        ["Zorlanırım, sürekli sorun yaşarız", 3],
        ["Görüşmek istemem", 4],
      ]),
      t("İlişkide güven konusu senin için ne ifade eder?", [
        ["Güven her şeydir, şeffaf davranırım", 1],
        ["Güven önemli ama temkinliyim", 2],
        ["Kolay güvenemem, sürekli test ederim", 3],
        ["Kimseye güvenmem, herkes yalan söyler", 4],
      ]),
      t("Partnerinle gelecek planları yaparken nasılsın?", [
        ["Birlikte plan yapar, hayal kurarız", 1],
        ["Benim planlarım var, ona da uyarsa", 2],
        ["Geleceği düşünmem, anı yaşarım", 3],
        ["Plan yapmam, zaten yürümeyecek", 4],
      ]),
      t("İlişkide en önemli şey sence nedir?", [
        ["Saygı, güven ve iletişim", 1],
        ["Sevgi ve anlayış", 2],
        ["Tutku ve heyecan", 3],
        ["Benim mutluluğum", 4],
      ]),
    ],
    results: [
      {
        title: "Olgun ve Bilge",
        description: "İlişki konusunda gerçekten olgun bir duruşun var. Anlayışlı, saygılı ve iletişime açık bir partnersin. Sağlıklı bir ilişki için gereken tüm özelliklere sahipsin.",
        advice: "Bu olgun duruşunu koru ve çevrendekilere de örnek ol. İlişkilerdeki başarının sırrı sende.",
        scoreRange: [20, 35],
      },
      {
        title: "Gelişmeye Açık",
        description: "İlişki olgunluğun genelde iyi ama bazı konularda kendini geliştirebilirsin. Bazen küçük takıntılar veya kıskançlıklar ilişkinin kalitesini etkileyebiliyor.",
        advice: "Kendini geliştirmeye açık olman en büyük artın. Özellikle güven ve iletişim konularında biraz daha çalışabilirsin.",
        scoreRange: [36, 50],
      },
      {
        title: "Dikkat Gerek",
        description: "İlişkilerde biraz daha olgunlaşmaya ihtiyacın var. Bencil veya kıskanç davranışların partnerini yoruyor olabilir. Kendi duygularının yanında partnerinin de ihtiyaçlarını görmelisin.",
        advice: "Empati yapmayı dene. Partnerinin yerine kendini koy ve onun da duyguları olduğunu unutma. Profesyonel destek almak iyi gelebilir.",
        scoreRange: [51, 65],
      },
      {
        title: "Olgunlaşması Gerek",
        description: "Maalesef ilişki konusunda henüz olgun sayılmazsın. Kıskançlık, öfke kontrolü ve bencillik konularında ciddi sıkıntıların var. Bu durum hem seni hem partnerini yıpratıyor.",
        advice: "Öncelikle kendinle barışmalı ve bir ilişkiye hazır olup olmadığını sorgulamalısın. Bir uzmandan destek alman şart.",
        scoreRange: [66, 80],
      },
    ],
  },
  {
    id: "sakinlik-ruhu",
    title: "Ne Kadar Sakin Bir Ruhun Var?",
    description: "Hayatın karmaşasında ne kadar sakin kalabiliyorsun? İç huzurunu test et.",
    icon: "🧘",
    questions: [
      t("Sabah alarmın çalmadığında ve geç kaldığında ne yaparsın?", [
        ["Sakin kalır, hızlıca hazırlanır çıkarım", 1],
        ["Hafif panikler ama toparlanırım", 2],
        ["Sinirle dolanır, etrafa bağırırım", 3],
        ["Yatağa geri yatıp 'bugün olmaz' derim", 4],
      ]),
      t("Bir proje üzerinde çalışırken bilgisayarın çökerse ne yaparsın?", [
        ["Derin nefes alır, yedekten devam ederim", 1],
        ["Tekrar dener, olmazsa yardım isterim", 2],
        ["Sinir krizi geçiririm", 3],
        ["Bilgisayarı kapatıp vazgeçerim", 4],
      ]),
      t("Sürekli telefonla arandığında ne hissedersin?", [
        ["Sakin cevaplar, ilgilenirim", 1],
        ["Biraz bunalırım ama cevaplarım", 2],
        ["Sinirle açıp bağırırım", 3],
        ["Telefonu kapatırım", 4],
      ]),
      t("Uzun bir kuyrukta beklerken ruh halin nasıldır?", [
        ["Müzik dinler, kitap okur, keyfimi yaparım", 1],
        ["Beklerim ama içten içe sıkılırım", 2],
        ["Sürekli şikayet eder, homurdanırım", 3],
        ["Kuyruğu bırakıp giderim", 4],
      ]),
      t("Bir arkadaşın sana çok önemli bir sırrını anlattığında ne yaparsın?", [
        ["Dinler, destek olur, sır saklarım", 1],
        ["Dikkatle dinler, yorum yapmam", 2],
        ["Heyecanlanır, hemen başkasına anlatırım", 3],
        ["Önem vermem, unuturum", 4],
      ]),
      t("Tatilde hava durumu berbatsa ne yaparsın?", [
        ["Alternatif planlar yapar, keyfime bakarım", 1],
        ["Biraz hayal kırıklığı yaşar ama uyum sağlarım", 2],
        ["Tatilin bittiğini söyleyip söylenirim", 3],
        ["Otel müdürüne bağırırım", 4],
      ]),
      t("Birisinin sana yalan söylediğini fark ettiğinde ne yaparsın?", [
        ["Sakin bir şekilde yüzleşirim", 1],
        ["Not eder, bir daha güvenmem", 2],
        ["Hemen yüzüne vurur, tartışma çıkarırım", 3],
        ["O kişiyi hayatımdan çıkarır, konuşmam", 4],
      ]),
      t("Kahveni döktüğünde ne yaparsın?", [
        ["'Olur böyle şeyler' deyip temizlerim", 1],
        ["Sessizce temizler, yenisini yaparım", 2],
        ["Sinirle temizler, söylenirim", 3],
        ["Bir şey fırlatır ya da tekme atarım", 4],
      ]),
      t("Favori programın yayından kaldırıldığında ne hissedersin?", [
        ["Başka dizi bulur, takmam", 1],
        ["Üzülürüm ama hayat devam", 2],
        ["Sosyal medyada tepki gösteririm", 3],
        ["Günlerce kötü hisseder, isyan ederim", 4],
      ]),
      t("Evin elektriği kesildiğinde ne yaparsın?", [
        ["Mum yakar, romantik bir akşam geçiririm", 1],
        ["Yetkiliyi arar, beklerim", 2],
        ["Sürekli şikayet ederim", 3],
        ["Komşulara bağırır, sinirimi onlardan çıkarırım", 4],
      ]),
      t("Topluluk önünde konuşma yapman gerektiğinde nasıl hissedersin?", [
        ["Heyecanlanırım ama üstesinden gelirim", 1],
        ["Biraz gergin olurum", 2],
        ["Çok utanır, kaçmak isterim", 3],
        ["Reddeder, asla çıkmam", 4],
      ]),
      t("Bir işi tam yetiştiremediğinde ne yaparsın?", [
        ["Durumu açıklar, yeni süre isterim", 1],
        ["Elimden geleni yapar, yetiştirmeye çalışırım", 2],
        ["Panikler, saçma hatalar yaparım", 3],
        ["Suçu başkasına atarım", 4],
      ]),
      t("Komşun yüksek sesle müzik dinlediğinde ne yaparsın?", [
        ["Kibarca rica ederim, kısmasını isterim", 1],
        ["Bir süre bekler, sonra uyarırım", 2],
        ["Duvara vurur, bağırırım", 3],
        ["Müziği açıp onunkiyle yarıştırırım", 4],
      ]),
      t("Yolda yürürken biri çarptığında ne yaparsın?", [
        ["'Önemli değil' deyip gülümserim", 1],
        ["Göz teması kurup başımı sallarım", 2],
        ["Arkamdan ters ters bakarım", 3],
        ["'Dikkat etsene!' diye bağırırım", 4],
      ]),
      t("Planların son anda iptal olduğunda nasıl tepki verirsin?", [
        ["Yeni plan yapar, esnek davranırım", 1],
        ["Biraz bozulurum ama kabullenirim", 2],
        ["Çok sinirlenir, günüm mahvolur", 3],
        ["O planı yapanı suçlar, trip atarım", 4],
      ]),
      t("Kalabalık bir ortamda yalnız hissettiğinde ne yaparsın?", [
        ["Keyfimi bilir, kimseye ihtiyaç duymam", 1],
        ["Birileriyle sohbet etmeye çalışırım", 2],
        ["Ortamdan sıkılır, erken kaçarım", 3],
        ["Ortamı terk eder, evime dönerim", 4],
      ]),
      t("Birisinin başarısını kıskandığında ne yaparsın?", [
        ["Onu tebrik eder, ilham alırım", 1],
        ["İçten içe kıskansam da kutlarım", 2],
        ["Başarısını küçümserim", 3],
        ["Onunla rekabete girer, ona zarar vermeye çalışırım", 4],
      ]),
      t("Haksız yere suçlandığında ne yaparsın?", [
        ["Sakin sakin açıklama yapar, kanıt sunarım", 1],
        ["Savunmama geçer, durumu anlatırım", 2],
        ["Hemen bağırıp çağırmaya başlarım", 3],
        ["Fiziksel tepki veririm", 4],
      ]),
      t("Hayal kırıklığına uğradığında toparlanman ne kadar sürer?", [
        ["Çabuk toparlanır, yoluma devam ederim", 1],
        ["Birkaç gün içinde toparlanırım", 2],
        ["Haftalarca etkisinden çıkamam", 3],
        ["Asla tam olarak toparlanamam", 4],
      ]),
      t("Meditasyon veya yoga gibi aktivitelere ne sıklıkla vakit ayırırsın?", [
        ["Düzenli olarak her gün yaparım", 1],
        ["Ara sıra denerim", 2],
        ["Hiç ilgimi çekmiyor", 3],
        ["Saçma buluyorum", 4],
      ]),
    ],
    results: [
      {
        title: "Buda Ruhu",
        description: "İç huzurun zirvesinde yaşıyorsun! Hiçbir şey seni sakinliğinden koparamaz. Farkındalığın yüksek, stres yönetimin mükemmel. Sen bir huzur dağısın.",
        advice: "Bu hali korumak için meditasyon ve farkındalık çalışmalarına devam et. Başkalarına da örnek oluyorsun.",
        scoreRange: [20, 35],
      },
      {
        title: "Dengeli Ruh",
        description: "Genelde sakin ve huzurlu bir insansın. Küçük aksiliklere takılmıyor, hayatın akışına güveniyorsun. Zaman zaman sarsılsan da toparlanmasını biliyorsun.",
        advice: "Sağlıklı bir iç dengeye sahipsin. Stresli anlarda derin nefes almayı unutma.",
        scoreRange: [36, 50],
      },
      {
        title: "Hareketli Ruh",
        description: "İç huzurun biraz dalgalı. Hayatın sürprizleri karşısında kolayca sarsılabiliyor, gerginlik yaşayabiliyorsun. İç sesini dinlemeye ve kendine zaman ayırmaya ihtiyacın var.",
        advice: "Düzenli olarak sessiz bir ortamda kendinle kal. Günlük tutmak ve yürüyüş yapmak sana iyi gelebilir.",
        scoreRange: [51, 65],
      },
      {
        title: "Fırtına Öncesi",
        description: "İç dünyan sürekli bir fırtına halinde! En ufak bir olay seni allak bullak ediyor. İç huzura kavuşmak için ciddi adımlar atman gerekiyor.",
        advice: "Profesyonel destek almayı düşün. Meditasyon, nefes çalışmaları ve düzenli egzersiz ile iç huzurunu yeniden inşa edebilirsin.",
        scoreRange: [66, 80],
      },
    ],
  },
  {
    id: "risk-ruhu",
    title: "Risk ve Macera Ruhun",
    description: "Ne kadar maceraperest olduğunu keşfet! Yeni deneyimlere açık mısın yoksa güvenli limanı mı tercih ediyorsun?",
    icon: "🚀",
    questions: [
      t("Yeni bir yemek dener misin?", [
        ["Her zaman, bilinmeyen tatlar beni heyecanlandırır", 1],
        ["Bazen denerim", 2],
        ["Sadece bildiğim şeyleri sipariş ederim", 3],
        ["Aynı şeyi yemekten mutluyum", 4],
      ]),
      t("Tatilde plansız bir macera yaşamak ister misin?", [
        ["Evet! Plansız tatil en iyisidir", 1],
        ["Biraz planlı biraz plansız", 2],
        ["Her şey planlı olmalı, stres olmamalı", 3],
        ["Tatile bile gitmem evim daha güvenli", 4],
      ]),
      t("Hiç bilmediğin bir şehirde kaybolduğunda ne hissedersin?", [
        ["Heyecanlanırım, keşif zamanı!", 1],
        ["Biraz tedirgin olurum ama keyfini çıkarırım", 2],
        ["Panikler, hemen yol bulmaya çalışırım", 3],
        ["Seyahat etmeyi sevmem", 4],
      ]),
      t("Paraşütle atlama gibi ekstrem bir spor yapar mısın?", [
        ["Kesinlikle, sıradaki hedefim bu!", 1],
        ["Belki bir gün cesaret edebilirim", 2],
        ["Korkarım, yapmam", 3],
        ["Kesinlikle delilik, asla yapmam", 4],
      ]),
      t("Kariyerinde radikal bir değişiklik yapar mısın?", [
        ["Evet, risk almaktan korkmam", 1],
        ["Düşünürüm, artıları eksileri tartarım", 2],
        ["Çok zor karar veririm", 3],
        ["Asla, mevcut düzenim güvende olmalı", 4],
      ]),
      t("Yeni bir hobi edinirken ne kadar istekli olursun?", [
        ["Hemen başlar, her şeyi denerim", 1],
        ["Araştırır, sonra başlarım", 2],
        ["Başlaması kolay şeyleri tercih ederim", 3],
        ["Hobim zaten var, yenisine gerek yok", 4],
      ]),
      t("Bir arkadaşın son anda değişen planlar için seni aradığında ne düşünürsün?", [
        ["Sürprizlere açığım, harika!", 1],
        ["Duruma göre karar veririm", 2],
        ["Rahatsız olurum, planımı bozma derim", 3],
        ["Asla plan değiştirmem", 4],
      ]),
      t("Yabancı biriyle sohbet başlatır mısın?", [
        ["Her zaman, her yerde sohbet ederim", 1],
        ["Bazen, ortama bağlı", 2],
        ["Çekinirim, genelde başlatmam", 3],
        ["Yabancılarla konuşmam", 4],
      ]),
      t("Yatırım yaparken ne tür araçlar tercih edersin?", [
        ["Kripto para, hisse senedi, yüksek risk", 1],
        ["Dengeli bir portföy oluştururum", 2],
        ["Mevduat faizi, düşük risk", 3],
        ["Parayı yastık altında tutarım", 4],
      ]),
      t("Bir yarışmaya katılmayı teklif etseler ne yaparsın?", [
        ["Hemen kabul eder, heyecanlanırım", 1],
        ["Düşünürüm, türüne bağlı", 2],
        ["Kesinlikle reddederim", 3],
        ["Sahneye bile çıkmam", 4],
      ]),
      t("Yeni bir teknoloji veya uygulamayı ne sıklıkla dersin?", [
        ["Çıkar çıkmaz hemen denerim", 1],
        ["Yorumları okuduktan sonra denerim", 2],
        ["Herkes kullanmaya başlayınca denerim", 3],
        ["Eski alışkanlıklarım bana yeter", 4],
      ]),
      t("Bir arkadaşın seni bir maceraya davet ettiğinde ilk tepkin ne olur?", [
        ["Nerede ve ne zaman?", 1],
        ["Detayları öğrenmek isterim", 2],
        ["Riskleri düşünür, temkinli yaklaşırım", 3],
        ["Hayır, teşekkürler derim", 4],
      ]),
      t("Yabancı bir ülkede yaşamayı düşünür müsün?", [
        ["Kesinlikle, çok isterim", 1],
        ["Belki bir süreliğine", 2],
        ["Zor olur, alışamayabilirim", 3],
        ["Asla, burada mutluyum", 4],
      ]),
      t("Bir fikrini herkesin önünde savunmaktan çekinir misin?", [
        ["Hiç çekinmem, fikrimi söylerim", 1],
        ["Ortama göre karar veririm", 2],
        ["Genelde sessiz kalırım", 3],
        ["Asla fikrimi söylemem", 4],
      ]),
      t("Yeni bir dil öğrenmeye başlar mısın?", [
        ["Evet, birkaç dil biliyorum ve yenilerini öğrenirim", 1],
        ["İsterim ama başlamak zor geliyor", 2],
        ["Zor ve zaman kaybı, gerek yok", 3],
        ["Dil öğrenmek bana göre değil", 4],
      ]),
      t("Rastgele bir otobüse binip nereye gittiğini görmek ister misin?", [
        ["Kesinlikle, harika bir macera olurdu", 1],
        ["Belki arkadaşımla birlikte", 2],
        ["Hiç güvenli gelmiyor", 3],
        ["Kesinlikle hayır", 4],
      ]),
      t("Yemek yaparken tarife harfiyen uyar mısın yoksa kendi yorumunu katar mısın?", [
        ["Asla tarife bakmam, tamamen içgüdüsel", 1],
        ["Tarife bakarım ama kendi dokunuşumu eklerim", 2],
        ["Tarife harfiyen uyarım", 3],
        ["Yemek yapmayı sevmem", 4],
      ]),
      t("Bir çatışmada arabuluculuk yapmayı teklif eder misin?", [
        ["Evet, hemen devreye girerim", 1],
        ["Bazen, ortama bağlı", 2],
        ["Karışmak istemem", 3],
        ["Kaçarım, bana ne", 4],
      ]),
      t("Fikrini değiştirmekte ne kadar zorlanırsın?", [
        ["Hiç zorlanmam, yeni bilgiyle değiştiririm", 1],
        ["Bazen ikna edilebilirim", 2],
        ["Zor ikna olurum", 3],
        ["Fikrim asla değişmez", 4],
      ]),
      t("Yılbaşı gecesi için ne tür planlar yaparsın?", [
        ["Bilinmeyen bir yerde doğaçlama kutlama", 1],
        ["Arkadaşlarla parti", 2],
        ["Evde aileyle", 3],
        ["Erken yatarım, yılbaşı benim için sıradan", 4],
      ]),
    ],
    results: [
      {
        title: "Sınır Tanımaz",
        description: "Macera senin ikinci adın! Risk almak, yeni şeyler denemek senin için hayatın anlamı. Duran bir hayat seni boğar, sürekli hareket halinde olmalısın. Korkusuz bir kaşifsin!",
        advice: "Bu enerjini güzel şeyler için kullan. Ancak bazen durup düşünmek de önemli, tüm riskler alınmaya değer olmayabilir.",
        scoreRange: [20, 35],
      },
      {
        title: "Maceraperest Ruh",
        description: "Yeni deneyimlere açıksın ve hayatı dolu dolu yaşamayı seviyorsun. Ancak akıllı riskler alıyor, tamamen gözü kara davranmıyorsun. Güzel bir dengen var.",
        advice: "Bu dengeni koru. Yeni deneyimlere açık ol ama önemli kararlarda artıları ve eksileri tart.",
        scoreRange: [36, 50],
      },
      {
        title: "Dengeli Yaklaşım",
        description: "Alışkanlıklarına bağlı, güvenli alanında kalmayı tercih eden bir yapın var. Büyük riskler almaz, bilinmezlikten hoşlanmazsın. Konfor alanın senin için önemli.",
        advice: "Bazen küçük adımlarla da olsa konfor alanından çıkmayı dene. Yeni deneyimler hayatına renk katabilir.",
        scoreRange: [51, 65],
      },
      {
        title: "Güvenli Liman",
        description: "Risk sana göre değil! Hayatında düzene, güvenceye ve bilinirliğe çok önem veriyorsun. Her şeyin kontrol altında olması seni rahatlatıyor.",
        advice: "Güvenlik ihtiyacın çok yüksek. Küçük adımlarla yeni şeyler dene, belki seversin. Hayat bazen sürprizleriyle güzeldir.",
        scoreRange: [66, 80],
      },
    ],
  },
  {
    id: "sabir-seviyesi",
    title: "Sabır Seviyen",
    description: "Ne kadar sabırlı bir insansın? Beklemek, dayanmak ve tahammül etmek konusundaki sınırlarını test et.",
    icon: "⏳",
    questions: [
      t("Süpermarkette uzun kuyrukta beklerken nasılsın?", [
        ["Sakin sıramı bekler, kitap okurum", 1],
        ["Beklerim ama içten içe sıkılırım", 2],
        ["Sürekli saate bakar, oflarım", 3],
        ["Kuyruğu bırakıp gider veya kavga çıkarırım", 4],
      ]),
      t("İnternet sayfasının yüklenmesi ne kadar sürerse sinirlenmeye başlarsın?", [
        ["1 dakikadan fazla olursa", 1],
        ["30 saniye", 2],
        ["10 saniye", 3],
        ["2 saniye geçse sinirlenirim", 4],
      ]),
      t("Bir bulmacayı çözerken ne kadar süre uğraşırsın?", [
        ["Saatlerce uğraşır, pes etmem", 1],
        ["Belli bir süre dener, sonra bakarım", 2],
        ["Hemen pes eder, cevaba bakarım", 3],
        ["Başlamam bile, sinir bozucu", 4],
      ]),
      t("Bir arkadaşın sürekli aynı hatayı yaptığında ne yaparsın?", [
        ["Her seferinde sabırla anlatır, destek olurum", 1],
        ["Birkaç kez anlatır, sonra bırakırım", 2],
        ["Hemen sinirlenir, bağırırım", 3],
        ["O arkadaşla görüşmeyi keserim", 4],
      ]),
      t("Bir eğitim veya kursta zorlandığında ne yaparsın?", [
        ["Sabırla çalışır, anlayana kadar devam ederim", 1],
        ["Biraz zorlansam da bırakmam", 2],
        ["Çabuk pes ederim", 3],
        ["Eğitimi suçlar, bırakır giderim", 4],
      ]),
      t("Sevdiğin bir yemeği yaparken tarif uzun sürdüğünde ne yaparsın?", [
        ["Adım adım uygular, keyfini çıkarırım", 1],
        ["Sabreder, güzel olacağını düşünürüm", 2],
        ["Kestirme yollar ararım", 3],
        ["Söylenir, sinirle pişiririm", 4],
      ]),
      t("Trafikte bebek ağlaması duyduğunda nasıl tepki verirsin?", [
        ["Anlayışlı olur, sakinleştirmeye çalışırım", 1],
        ["Rahatsız olurum ama ses etmem", 2],
        ["Sabrım taşar, bağırırım", 3],
        ["Arabanı terk eder, yürür giderim", 4],
      ]),
      t("Bir işi öğrenirken ne kadar sabredersin?", [
        ["Öğrenene kadar defalarca denerim", 1],
        ["Birkaç denemeden sonra yardım isterim", 2],
        ["İki denemede pes ederim", 3],
        ["Hiç denemem, yapamam zaten", 4],
      ]),
      t("Müşteri hizmetlerini aradığında uzun süre beklemek zorunda kalırsan?", [
        ["Müzik açar, sakin sakin beklerim", 1],
        ["Biraz bekler, sonra tekrar ararım", 2],
        ["Sürekli tuşlara basar, şikayet ederim", 3],
        ["Telefonu fırlatır, arıza çıkarırım", 4],
      ]),
      t("Uzun süreli bir proje üzerinde çalışırken motivasyonunu nasıl korursun?", [
        ["Küçük hedefler koyar, ilerlemeyi kutlarım", 1],
        ["Düzenli çalışır, ara ara mola veririm", 2],
        ["Sıkılır, başka projeye geçerim", 3],
        ["Projeyi yarıda bırakırım", 4],
      ]),
      t("Birisinin konuşmasını bitirmesini beklerken nasılsın?", [
        ["Sonuna kadar saygıyla dinlerim", 1],
        ["Dinlerim ama araya giresim gelir", 2],
        ["Sık sık araya girerim", 3],
        ["Hiç dinlemem, kendi bildiğimi okurum", 4],
      ]),
      t("Her gün küçük ama düzenli bir alışkanlık edinmekte ne kadar başarılısın?", [
        ["Çok başarılıyım, disiplinliyim", 1],
        ["Bazen aksatırım ama devam ederim", 2],
        ["Bir hafta sonra bırakırım", 3],
        ["Hiç alışkanlık edinemiyorum", 4],
      ]),
      t("Bir oyunda zor bir seviyede takılıp kalırsan ne yaparsın?", [
        ["Stratejimi değiştirir, denerim", 1],
        ["Birkaç kez dener, video izlerim", 2],
        ["Hemen sinirlenir, oyunu kapatırım", 3],
        ["Kumandayı duvara fırlatırım", 4],
      ]),
      t("Randevuna 30 dakika geç kalan birini ne kadar süre beklersin?", [
        ["1 saatten fazla, merak ederim", 1],
        ["30 dakika daha beklerim", 2],
        ["15 dakika bekler giderim", 3],
        ["5 dakika geçse giderim", 4],
      ]),
      t("Yemek siparişin geç geldiğinde ne yaparsın?", [
        ["Anlayışlı olur, yoğun olduklarını bilirim", 1],
        ["Biraz gecikince arar sorarım", 2],
        ["Sinirlenir, şikayet ederim", 3],
        ["Siparişi iptal eder, restoranı arar bağırırım", 4],
      ]),
      t("Bir kitabı okurken sıkıcı bir bölüme geldiğinde ne yaparsın?", [
        ["Sabırla okur, sonra güzelleşeceğini bilirim", 1],
        ["Hızlıca geçer, atlarım", 2],
        ["Kitabı bırakırım", 3],
        ["Kitap okumayı sevmem zaten", 4],
      ]),
      t("Bir hobi edinmek için ne kadar süre emek verirsin?", [
        ["Usta olana kadar yıllarca çalışırım", 1],
        ["İyi seviyeye gelene kadar", 2],
        ["Birkaç denemeden sonra sıkılırım", 3],
        ["Hiç başlamam, çünkü bırakacağımı bilirim", 4],
      ]),
      t("Sevmediğin bir işi yapmak zorunda kaldığında nasılsın?", [
        ["İşin en iyisini yapar, bitiririm", 1],
        ["Yaparım ama söylene söylene", 2],
        ["İşi savsaklar, geçiştiririm", 3],
        ["Yapmam, başkası yapsın", 4],
      ]),
      t("Bir ilişkide sorunları çözmek için ne kadar süre uğraşırsın?", [
        ["Sorun çözülene kadar her yolu denerim", 1],
        ["Bir süre dener, olmazsa bırakırım", 2],
        ["Hemen pes eder, kaçarım", 3],
        ["Hiç uğraşmam, direkt biterim", 4],
      ]),
      t("Yeni bir şehirde kaybolduğunda ne kadar süre kendi başına bulmaya çalışırsın?", [
        ["Saatlerce keşfeder, zevk alırım", 1],
        ["Bir süre dener, bulamazsam sorarım", 2],
        ["Hemen telefonuma bakar, navigasyon açarım", 3],
        ["Panikler, hemen taksi çağırırım", 4],
      ]),
    ],
    results: [
      {
        title: "Sabır Abidesi",
        description: "Sabır konusunda efsanesin! Hiçbir şey seni yolundan alıkoyamaz. Zorluklar karşısında metanetini koruyor, her durumda sakin kalabiliyorsun. Bu özelliğin sayesinde büyük işler başarıyorsun.",
        advice: "Bu büyük sabrını ve kararlılığını koru. Örnek alınacak bir duruşun var.",
        scoreRange: [20, 35],
      },
      {
        title: "Dengeli Liman",
        description: "Normal bir sabır seviyen var. Gerektiğinde sabredebilir, gerektiğinde harekete geçebilirsin. Hayatın zorluklarıyla başa çıkma konusunda sağlıklı bir dengeye sahipsin.",
        advice: "Bu dengeyi koruman önemli. Zorlandığın anlarda derin nefes almayı unutma.",
        scoreRange: [36, 50],
      },
      {
        title: "Telaşlı Ruh",
        description: "Sabrın biraz kısa. Hemen sonuç almak istiyor, beklemekten hoşlanmıyorsun. Bu aceleciliğin bazen hatalı kararlar almana neden olabiliyor.",
        advice: "Beklemenin de değerli olduğunu hatırla. Büyük işler zaman ister, acele etme.",
        scoreRange: [51, 65],
      },
      {
        title: "Anında Patlama",
        description: "Sabır konusunda ciddi sıkıntıların var! Hemen her şeyin olmasını istiyor, en ufak gecikmede çileden çıkıyorsun. Bu durum hem seni hem çevrendekileri yoruyor.",
        advice: "Sabrını geliştirmek için farkındalık egzersizleri yap. Beklerken nefesine odaklan ve acele etmek zorunda olmadığını hatırla.",
        scoreRange: [66, 80],
      },
    ],
  },
  {
    id: "empati-gucu",
    title: "Empati Gücün",
    description: "Başkalarının duygularını ne kadar anlayabiliyorsun? Empati yeteneğini ölç ve keşfet.",
    icon: "💞",
    questions: [
      t("Bir arkadaşın üzgün olduğunu söylemeden belli ediyorsa ne yaparsın?", [
        ["Hemen fark eder, yanına gider sorarım", 1],
        ["Belli eder ama hemen müdahale etmem", 2],
        ["Fark etmem, anlamam", 3],
        ["Kendi derdim yeter, ilgilenmem", 4],
      ]),
      t("Bir filmde üzücü bir sahne izlediğinde ne hissedersin?", [
        ["Karakterlerle birlikte ağlarım", 1],
        ["Duygulanırım ama kendimi tutarım", 2],
        ["Hiçbir şey hissetmem", 3],
        ["Film izlemeyi sevmem", 4],
      ]),
      t("Bir tanıdığının başına kötü bir olay geldiğini duyduğunda ne yaparsın?", [
        ["Hemen ulaşır, yardım teklif ederim", 1],
        ["Geçmiş olsun mesajı atarım", 2],
        ["Üzülürüm ama bir şey yapmam", 3],
        ["Başkalarına anlatır, dedikodusunu yaparım", 4],
      ]),
      t("Evsiz bir insan gördüğünde ne hissedersin?", [
        ["İçim parçalanır, yardım etmek isterim", 1],
        ["Üzülürüm ama geçip giderim", 2],
        ["Görmezden gelirim", 3],
        ["Neden evsiz olduğunu sorgular, yargılarım", 4],
      ]),
      t("Bir arkadaşın sana bir sorununu anlattığında nasıl dinlersin?", [
        ["Tüm dikkatimle dinler, sorular sorarım", 1],
        ["Dinlerim, bazen tavsiye veririm", 2],
        ["Yarısını dinler, diğer yarısında kendimi anlatırım", 3],
        ["Sıkılır, konuyu değiştiririm", 4],
      ]),
      t("Birisi topluluk içinde küçük düştüğünde ne hissedersin?", [
        ["Onun yerine ben utanır, yardım etmek isterim", 1],
        ["Geçmiş olsun der gibi bakarım", 2],
        ["Komik bulur, gülerim", 3],
        ["Hak etmiştir diye düşünürüm", 4],
      ]),
      t("Bir arkadaşın bir başarı elde ettiğinde onun heyecanını paylaşır mısın?", [
        ["İçtenlikle kutlar, heyecanlanırım", 1],
        ["Tebrik eder, geçerim", 2],
        ["Kıskanır, belli etmem", 3],
        ["Görmezden gelirim veya küçümserim", 4],
      ]),
      t("Bir kavga anında iki tarafı da dinler misin?", [
        ["Her zaman, herkesi anlamaya çalışırım", 1],
        ["Bazen dinler, bazen taraf tutarım", 2],
        ["Karışmam, uzak dururum", 3],
        ["Hemen taraf seçer, suçlu ararım", 4],
      ]),
      t("Bir hayvanın acı çektiğini gördüğünde ne yaparsın?", [
        ["Hemen yardım eder, veterinere götürürüm", 1],
        ["Üzülür, başkasının yardım etmesini dilerim", 2],
        ["Görmezden gelirim", 3],
        ["Hayvanlarla ilgilenmem", 4],
      ]),
      t("Birisinin seninle aynı fikirde olmadığında nasıl tepki verirsin?", [
        ["Anlamaya çalışır, saygı duyarım", 1],
        ["Dinlerim ama ikna etmeye çalışırım", 2],
        ["Hemen karşı çıkar, tartışırım", 3],
        ["Aptal olduğunu düşünür, ciddiye almam", 4],
      ]),
      t("Sevdiğin birinin canının yandığını gördüğünde fiziksel olarak acı hisseder misin?", [
        ["Evet, onun acısını bedenimde hissederim", 1],
        ["Biraz hissederim", 2],
        ["Sadece üzülürüm", 3],
        ["Hiçbir şey hissetmem", 4],
      ]),
      t("Birisinin iyi bir haberi olduğunda onun adına mutlu olur musun?", [
        ["Kesinlikle, içtenlikle sevinirim", 1],
        ["Mutlu olurum", 2],
        ["Kıskanmasam da pek umrumda olmaz", 3],
        ["Benim de olsaydı keşke derim", 4],
      ]),
      t("Bir arkadaşın sürekli şikayet ediyorsa ne yaparsın?", [
        ["Sabırla dinler, çözüm bulmasına yardım ederim", 1],
        ["Bir süre dinler, sonra sabrım tükenir", 2],
        ["'Sus artık' der, sinirlenirim", 3],
        ["O arkadaşla görüşmeyi keserim", 4],
      ]),
      t("Birinin gözlerindeki ifadeden ne hissettiğini anlayabilir misin?", [
        ["Evet, çok iyi anlarım", 1],
        ["Bazen anlarım", 2],
        ["Zorlanırım", 3],
        ["Hiç anlamam", 4],
      ]),
      t("Bir arkadaşın sessiz ve içine kapanık olduğunda ne yaparsın?", [
        ["Yanına gider, konuşması için baskı yapmam, sadece orada olduğumu hissettiririm", 1],
        ["Sorun ne diye sorarım", 2],
        ["Fark etmem", 3],
        ["'Bırak kendi halinde' der, uzaklaşırım", 4],
      ]),
      t("Birinin arkasından konuşulduğunu duyduğunda ne yaparsın?", [
        ["Konuşanları uyarır, savunurum", 1],
        ["İçimden rahatsız olur ama karışmam", 2],
        ["Ben de katılır, dedikodu yaparım", 3],
        ["O kişiye gidip anlatır, fitne çıkarırım", 4],
      ]),
      t("Kendini başkalarının yerine koymakta ne kadar başarılısın?", [
        ["Çok başarılıyım, herkesin perspektifinden bakabilirim", 1],
        ["İyi sayılırım", 2],
        ["Zorlanırım", 3],
        ["Sadece kendi bakış açım var", 4],
      ]),
      t("Bir trafik kazası gördüğünde ilk tepkin ne olur?", [
        ["Hemen yardıma koşarım", 1],
        ["112'yi ararım", 2],
        ["Oradan uzaklaşırım", 3],
        ["Fotoğraf çeker, sosyal medyada paylaşırım", 4],
      ]),
      t("Bir çocuğun ağladığını duyduğunda ne hissedersin?", [
        ["İçim cız eder, neden ağladığını merak ederim", 1],
        ["Rahatsız olurum", 2],
        ["Can sıkıcı bulurum", 3],
        ["Duymazdan gelirim", 4],
      ]),
      t("Birinin size kızgın olduğunu hissettiğinde ne yaparsın?", [
        ["Konuşur, ne olduğunu anlamaya çalışırım", 1],
        ["Zaman verir, sonra konuşurum", 2],
        ["Ben de kızar, mesafe koyarım", 3],
        ["Trip atar, konuşmam", 4],
      ]),
    ],
    results: [
      {
        title: "Empati Devi",
        description: "Empati konusunda olağanüstüsün! İnsanların duygularını derinden hissediyor, onları anlıyor ve destek oluyorsun. Çevrendekiler için gerçek bir şifa kaynağısın. Duygusal zekan çok yüksek.",
        advice: "Bu yeteneğini koru ve gerektiğinde sınır koymayı da unutma. Başkalarına yardım ederken kendini ihmal etme.",
        scoreRange: [20, 35],
      },
      {
        title: "Duyarlı Kalp",
        description: "Empati seviyen iyi. Genelde insanları anlıyor ve onlara destek oluyorsun. Bazen kendi duyguların ağır bassa da çevrendekilere karşı duyarlısın.",
        advice: "Bu güzel özelliğini geliştirmeye devam et. Aktif dinleme pratikleriyle empatini daha da güçlendirebilirsin.",
        scoreRange: [36, 50],
      },
      {
        title: "Mesafeli Durum",
        description: "Empati konusunda biraz mesafelisın. İnsanların duygularını anlamakta zorlanıyor veya umursamıyor olabilirsin. Duygusal bağ kurmak senin için öncelik değil.",
        advice: "Küçük adımlarla başkalarının duygularına daha fazla dikkat etmeyi dene. Birinin yerine kendini koymak, ilişkilerini güçlendirebilir.",
        scoreRange: [51, 65],
      },
      {
        title: "Duygusal Buzdağı",
        description: "Empati konusunda ciddi eksiklerin var. Başkalarının duygularını anlamakta zorlanıyor, hatta umursamıyorsun. Bu durum ilişkilerinde sorunlara yol açıyor olabilir.",
        advice: "Empati geliştirilebilir bir beceridir. Küçük adımlarla başla: önce dinle, anlamaya çalış, yargılama. Bir uzmandan destek almak faydalı olabilir.",
        scoreRange: [66, 80],
      },
    ],
  },
  {
    id: "sosyal-kelebek",
    title: "Sosyal Kelebek misin?",
    description: "Sosyal bir insan mısın yoksa yalnızlığı mı seviyorsun? Sosyal enerjini ve insan ilişkilerindeki duruşunu keşfet.",
    icon: "🦋",
    questions: [
      t("Bir partide kendini nasıl hissedersin?", [
        ["Odanın enerjisi olur, herkesle kaynaşırım", 1],
        ["Keyif alırım ama bir süre sonra yorulurum", 2],
        ["Bir köşede oturur, gözlem yaparım", 3],
        ["Hiç gitmem, kalabalıklardan hoşlanmam", 4],
      ]),
      t("Yeni insanlarla tanışmak senin için nasıl bir deneyim?", [
        ["Heyecan verici, her yeni insan yeni bir dünya", 1],
        ["Keyiflidir ama biraz çaba gerektirir", 2],
        ["Zorlanırım, utangaçımdır", 3],
        ["İstemem, yeni insanlara güvenmem", 4],
      ]),
      t("Hafta sonu ne yapmayı tercih edersin?", [
        ["Arkadaşlarla dışarı çıkmak, sosyalleşmek", 1],
        ["Küçük bir grupla bir şeyler yapmak", 2],
        ["Evde film izlemek, yalnız vakit geçirmek", 3],
        ["Kimseyi görmemek, tamamen yalnız kalmak", 4],
      ]),
      t("Sosyal medyada ne sıklıkla paylaşım yaparsın?", [
        ["Her gün birkaç kere, hayatımın her anını paylaşırım", 1],
        ["Haftada birkaç kere", 2],
        ["Ayda bir", 3],
        ["Hiç paylaşım yapmam", 4],
      ]),
      t("Bir ortama girdiğinde tanımadığın biriyle sohbet başlatır mısın?", [
        ["Kesinlikle, herkesle sohbet ederim", 1],
        ["Bazen, ortam uygunsa", 2],
        ["Genelde başlatmam", 3],
        ["Asla, çok zorlanırım", 4],
      ]),
      t("Yalnız kalmak seni nasıl hissettirir?", [
        ["Hiç sevmem, hemen birini ararım", 1],
        ["Ara sıra iyi gelir ama çok fazla değil", 2],
        ["Keyif alırım, yalnızlığı severim", 3],
        ["En mutlu olduğum anlar yalnız olduğum anlar", 4],
      ]),
      t("Bir arkadaş grubunda genelde hangi roldesin?", [
        ["Organizatör, herkesi bir araya getiren kişi", 1],
        ["Kaynaştırıcı, ortamı yumuşatan", 2],
        ["Dinleyici, sessiz ama orada olan", 3],
        ["Yok sayılan veya gruba ait hissetmeyen", 4],
      ]),
      t("Telefonunda kaç kişiyle düzenli mesajlaşırsın?", [
        ["50'den fazla, sürekli iletişim halindeyim", 1],
        ["10-20 kişi", 2],
        ["3-5 kişi", 3],
        ["Sadece ailemle", 4],
      ]),
      t("Bir iş yemeğinde veya kurumsal etkinlikte nasılsın?", [
        ["Odanın en dışa dönük kişisiyim", 1],
        ["Gerekli sohbetleri yapar, sonra sessizleşirim", 2],
        ["Mecbur kalınca konuşurum", 3],
        ["Mümkünse hiç katılmam", 4],
      ]),
      t("Arkadaşların seni nasıl tanımlar?", [
        ["Hayatın enerjisi, sürekli hareket halinde", 1],
        ["Güvenilir ve eğlenceli", 2],
        ["Sessiz ve sakin", 3],
        ["İçine kapanık ve yalnız", 4],
      ]),
      t("Bir etkinliğe gitmek yerine evde kalmayı tercih eder misin?", [
        ["Nadiren, dışarı çıkmayı tercih ederim", 1],
        ["Bazen, ruh halime bağlı", 2],
        ["Sıklıkla evde kalmayı tercih ederim", 3],
        ["Hemen hemen her zaman", 4],
      ]),
      t("Topluluk önünde konuşma yapmak senin için ne ifade eder?", [
        ["Keyifli ve heyecan verici", 1],
        ["Yapabilirim ama gergin olurum", 2],
        ["Zorlanırım, mümkünse kaçınırım", 3],
        ["Korkunç bir fikir, asla yapamam", 4],
      ]),
      t("Yeni bir arkadaşlık kurmak için ne yaparsın?", [
        ["İlk adımı ben atar, samimi davranırım", 1],
        ["Ortak nokta bulursam yakınlaşırım", 2],
        ["Karşı tarafın adım atmasını beklerim", 3],
        ["Yeni arkadaşlık arayışım yok", 4],
      ]),
      t("Bir grup projesinde nasıl çalışırsın?", [
        ["Liderlik yapar, herkesi yönlendiririm", 1],
        ["Aktif katkı sağlar, iş birliği yaparım", 2],
        ["Üzerime düşeni yapar, sessiz kalırım", 3],
        ["Mümkünse tek başıma çalışmayı tercih ederim", 4],
      ]),
      t("Sosyal ortamlarda ne sıklıkla telefonuna bakarsın?", [
        ["Neredeyse hiç, insanlarla ilgilenirim", 1],
        ["Ara sıra göz atarım", 2],
        ["Sık sık telefonuma bakarım", 3],
        ["Sürekli telefonumdayım", 4],
      ]),
      t("Bir arkadaşının doğum gününü kutlar mısın?", [
        ["Herkese sürpriz parti düzenlerim", 1],
        ["Mesaj atar veya ararım", 2],
        ["Sosyal medyada kutlarım", 3],
        ["Genelde unuturum", 4],
      ]),
      t("Dans etmeyi sever misin?", [
        ["Bayılırım! İlk ben kalkarım dansa", 1],
        ["Eğlencelidir, bazen", 2],
        ["Utandığım için dans etmem", 3],
        ["Müzik dinlemeyi bile sevmem", 4],
      ]),
      t("Bir kafede tek başına otururken nasıl hissedersin?", [
        ["Rahatsız olurum, yanımda biri olmalı", 1],
        ["Normaldir, kitap okurum", 2],
        ["Keyif alırım, kendimle kalırım", 3],
        ["Tek başıma hiçbir yere gitmem", 4],
      ]),
      t("Tanımadığın biriyle asansörde yalnız kaldığında ne yaparsın?", [
        ["Sohbet başlatır, günün nasıl diye sorarım", 1],
        ["Gülümser, selam veririm", 2],
        ["Telefonuma bakar, ilgilenmezim", 3],
        ["Göz temasından kaçınır, duvara dönerim", 4],
      ]),
      t("Kaç yakın arkadaşın var?", [
        ["Çok sayıda, herkese arkadaşım derim", 1],
        ["5-10 arası gerçek arkadaşım var", 2],
        ["2-3 tane çok yakın arkadaşım var", 3],
        ["Yok denecek kadar az, yalnızımdır", 4],
      ]),
    ],
    results: [
      {
        title: "Sosyal Kelebek",
        description: "Sen tam bir sosyal kelebeksin! İnsanlarla iç içe olmaktan büyük keyif alıyor, enerjini sosyal ortamlardan alıyorsun. Her ortamda aranan, sevilen birisin. Sosyal çevren çok geniş.",
        advice: "Sosyal enerjini beslemeye devam et. Yalnız kalman gerektiğinde de kendine zaman ayırmayı unutma, denge önemli.",
        scoreRange: [20, 35],
      },
      {
        title: "Dengeli Sosyal",
        description: "Sosyalleşmeyi seviyorsun ama yalnız kalmaktan da keyif alıyorsun. İnsanlarla vakit geçirmekle kendi başına olmak arasında güzel bir dengen var. Bu denge sağlıklı bir yaşam için ideal.",
        advice: "Bu dengeni koru. Gerektiğinde sosyalleş, gerektiğinde yalnız kal ve iç sesini dinle.",
        scoreRange: [36, 50],
      },
      {
        title: "Sessiz Sakin",
        description: "Sosyal ortamlarda pek aktif değilsin. Küçük grupları veya yalnız zamanı tercih ediyorsun. Bu seni mutlu ediyorsa sorun yok, herkes sosyal olmak zorunda değil.",
        advice: "Kendini rahat hissettiğin ortamlarda bulunmaya özen göster. Sosyalleşmek için kendini zorlama, ama tamamen de izole olma.",
        scoreRange: [51, 65],
      },
      {
        title: "Yalnız Kurt",
        description: "Yalnızlığı tercih eden, insanlardan uzak duran bir yapın var. Sosyal ortamlar seni yoruyor, hatta rahatsız ediyor olabilir. Kendi dünyanda mutlusun.",
        advice: "Yalnızlık güzel bir şey ama tamamen izolasyon depresyona yol açabilir. Küçük adımlarla da olsa güvendiğin insanlarla zaman geçirmeyi dene.",
        scoreRange: [66, 80],
      },
    ],
  },
  {
    id: "stres-seviyesi",
    title: "Stres Altında Nasılsın?",
    description: "Stresle başa çıkma yeteneğini test et. Hayatın baskıları karşısında ne kadar dirençli olduğunu keşfet.",
    icon: "🧠",
    questions: [
      t("Son anda yetiştirmen gereken bir iş olduğunda nasıl hissedersin?", [
        ["Sakin kalır, plan yaparım", 1],
        ["Hafif gergin olurum ama odaklanırım", 2],
        ["Panikler, ne yapacağımı şaşırırım", 3],
        ["Sinir krizi geçiririm", 4],
      ]),
      t("Ne sıklıkla baş ağrısı veya fiziksel stres belirtileri yaşarsın?", [
        ["Neredeyse hiç", 1],
        ["Ayda birkaç kere", 2],
        ["Haftada birkaç kere", 3],
        ["Neredeyse her gün", 4],
      ]),
      t("Uyku kaliten nasıl?", [
        ["Harika, hemen dalar ve deliksiz uyurum", 1],
        ["Genelde iyi, bazen bölünür", 2],
        ["Sık sık uyanır, zor uyurum", 3],
        ["Uykusuzluk çekiyorum", 4],
      ]),
      t("Bir sorunla karşılaştığında ilk tepkin ne olur?", [
        ["Sakin analiz eder, çözüm ararım", 1],
        ["Biraz endişelenir ama sonra toparlarım", 2],
        ["Hemen en kötü senaryoyu düşünürüm", 3],
        ["Yıkılır, paniklerim", 4],
      ]),
      t("İş/okul hayatında ne kadar baskı hissediyorsun?", [
        ["Neredeyse hiç, keyif alıyorum", 1],
        ["Normal düzeyde baskı var", 2],
        ["Oldukça fazla baskı altındayım", 3],
        ["Dayanılmaz düzeyde stres içindeyim", 4],
      ]),
      t("Stresli anlarda ne sıklıkla derin nefes alırsın?", [
        ["Her zaman bilinçli nefes alırım", 1],
        ["Bazen hatırlarım", 2],
        ["Nadiren aklıma gelir", 3],
        ["Hiç yapmam", 4],
      ]),
      t("Bir hafta içinde kaç kere kendini aşırı gergin hissedersin?", [
        ["Hiç", 1],
        ["1-2 kere", 2],
        ["3-5 kere", 3],
        ["Her gün", 4],
      ]),
      t("Hayatındaki belirsizliklerle nasıl başa çıkarsın?", [
        ["Kabullenir, akışına bırakırım", 1],
        ["Plan yapar, belirsizliği azaltmaya çalışırım", 2],
        ["Sürekli endişelenirim", 3],
        ["Belirsizlik beni felç eder", 4],
      ]),
      t("Dinlenmek ve rahatlamak için ne sıklıkla zaman ayırırsın?", [
        ["Her gün düzenli olarak", 1],
        ["Haftada birkaç kere", 2],
        ["Nadiren", 3],
        ["Hiç vakit bulamıyorum", 4],
      ]),
      t("Sosyal ilişkilerin stres seviyeni nasıl etkiliyor?", [
        ["Stresimi azaltır, beni rahatlatır", 1],
        ["Genelde iyi gelir", 2],
        ["Bazen stres kaynağıdır", 3],
        ["Sürekli stres kaynağım", 4],
      ]),
      t("Bir gün içinde kaç kere sinirlenirsin?", [
        ["Hiç veya çok nadir", 1],
        ["1-2 kere", 2],
        ["3-5 kere", 3],
        ["10'dan fazla", 4],
      ]),
      t("Kendini sürekli meşgul ve yorgun hissediyor musun?", [
        ["Hayır, dengeli bir hayatım var", 1],
        ["Bazen yoğun olur", 2],
        ["Sık sık yorgun hissediyorum", 3],
        ["Sürekli tükenmiş hissediyorum", 4],
      ]),
      t("Yeni bir durum veya ortama uyum sağlamakta zorlanır mısın?", [
        ["Çok kolay uyum sağlarım", 1],
        ["Biraz zaman alır ama uyum sağlarım", 2],
        ["Zorlanırım", 3],
        ["Hiç uyum sağlayamam", 4],
      ]),
      t("Hobilerine ne sıklıkla vakit ayırabiliyorsun?", [
        ["Düzenli olarak her gün", 1],
        ["Haftada birkaç kere", 2],
        ["Ayda bir, çok nadir", 3],
        ["Hiç vaktim yok", 4],
      ]),
      t("Kendini suçlu hissetme sıklığın nedir?", [
        ["Neredeyse hiç", 1],
        ["Bazen", 2],
        ["Sık sık", 3],
        ["Sürekli kendimi suçlarım", 4],
      ]),
      t("Bir kriz anında nasıl karar verirsin?", [
        ["Sakin ve mantıklı kararlar alırım", 1],
        ["Biraz tereddütle ama karar veririm", 2],
        ["Panikle ani kararlar alırım", 3],
        ["Hiç karar veremem, donup kalırım", 4],
      ]),
      t("Kafein veya şeker tüketimin stresle ilişkili mi?", [
        ["Düzenli ve dengeli tüketirim", 1],
        ["Biraz artış olmuş olabilir", 2],
        ["Stresliyken çok daha fazla tüketirim", 3],
        ["Tamamen bağımlıyım", 4],
      ]),
      t("Bir tartışma sonrası ne kadar sürede sakinleşirsin?", [
        ["Hemen, 5 dakika içinde", 1],
        ["Bir saat içinde", 2],
        ["Birkaç saat içinde", 3],
        ["Günlerce etkisinden çıkamam", 4],
      ]),
      t("Hayatının kontrolü sende mi yoksa olayların seni yönettiğini mi hissediyorsun?", [
        ["Kesinlikle kontrol bende", 1],
        ["Çoğu zaman kontrol bende", 2],
        ["Bazen kontrolü kaybediyorum", 3],
        ["Hayatım beni yönetiyor", 4],
      ]),
      t("Bir gün içinde ne sıklıkla gülümser veya kahkaha atarsın?", [
        ["Sürekli, çok sık gülerim", 1],
        ["Sık sık gülerim", 2],
        ["Ara sıra", 3],
        ["Çok nadir", 4],
      ]),
    ],
    results: [
      {
        title: "Stres Aslanı",
        description: "Stres yönetiminde ustasın! Hayatın zorlukları karşısında sakinliğini koruyor, her durumda çözüm odaklı kalabiliyorsun. Sağlam bir ruhsal yapın var.",
        advice: "Bu güçlü yönünü koru. Kendine de iyi bakmayı unutma, güçlü olmak her zaman her şeyi kaldırmak demek değil.",
        scoreRange: [20, 35],
      },
      {
        title: "Dengeli Duruş",
        description: "Stresle başa çıkma konusunda genellikle iyisin. Normal hayatın getirdiği baskılarla baş edebiliyor, gerektiğinde rahatlamayı biliyorsun. Dengeli bir yaşamın var.",
        advice: "Mevcut dengeni korumaya devam et. Stres seviyen yükseldiğinde nefes egzersizleri ve kısa molalarla kendini toparlayabilirsin.",
        scoreRange: [36, 50],
      },
      {
        title: "Gergin Ruh",
        description: "Stres seviyen normalin üzerinde. Hayatın baskıları seni zorluyor ve bu durum hem fiziksel hem zihinsel sağlığını etkiliyor olabilir. Biraz yavaşlamaya ihtiyacın var.",
        advice: "Stres yönetimi tekniklerini dene. Düzenli egzersiz, meditasyon ve hobilerine vakit ayırmak stresini azaltabilir. Gerekirse profesyonel destek al.",
        scoreRange: [51, 65],
      },
      {
        title: "Tükenmiş Nokta",
        description: "Stres seviyen alarm veriyor! Kronik stres altında olduğun ve bunun hayatının her alanını etkilediği çok açık. Acilen dinlenmeye, destek almaya ve hayatında köklü değişiklikler yapmaya ihtiyacın var.",
        advice: "Öncelikle bir doktora veya terapiste başvur. Kendine zaman ayır, tatil yap, hayatında stres kaynaklarını azalt. Sağlığın her şeyden önemli.",
        scoreRange: [66, 80],
      },
    ],
  },
];