export type SignGuide = {
  overview: string;
  love: string;
  career: string;
  strengths: string;
  element: string;
};

export const SIGN_GUIDES_UPDATED = "2026-10-07";

export const SIGN_GUIDES: Record<string, SignGuide> = {
  Koç: {
    overview:
      "Koç, Zodyak'ın ilk burcu ve zodyak çarkının start düğmesidir; doğduğu andan itibaren harekete geçmek, başlamak ve önde olmak ister. Yaşam enerjisi yüksektir, bir işe kara verdiğinde uzun uzadıya düşünmez, deneyerek öğrenir. Öncü niteliği onu doğuştan bir girişimci ve başlatıcı yapar: kriz anlarında ilk hamleyi yapan, etrafındakilere yön veren kişidir. Motivasyonu nettir — kazanmak, ilerlemek, bir iz bırakmak. Bu güçlü itki, sabırsızlık ve tahammülsüzlük gibi gölgeleri de beraberinde getirir; Koç'un olgunlaşma yolculuğu, ateşi yakarken yanında suyu da taşımayı öğrenmesiyle tamamlanır. Sabrı öğrendiğinde, Zodyak'ın bu ilk kıvılcımı kontrol edilebilir bir güce dönüşür.",
    love:
      "Aşkta Koç, avcı ruhlu ve tutkuludur: ilk görüşte başlayan bir çekim, hızla büyüyen bir heyecan ve dobra bir flört dili. Partnerine karşı oyun oynamaz, ne hissettiğini net söyler; ilişkide de hayatın her alanında olduğu gibi öncü olmak ister. Romantik jestler ve sürprizler onu canlı tutar, rutin ise onu söndürür. İlişki dilinde doğrudanlığı kırıcı olabilir; partnerinin duygularını okumayı ve beklemeyi öğrenmesi, tutkusunu kalıcı bir bağga dönüştürür. Sadık kalır ama özgür alana ihtiyacı olduğunu da açıkça ister.",
    career:
      "İş hayatında Koç, hız ve inisiyatif adamıdır: girişimcilik, satış, spor, operasyon yöneticiliği, acil durum ve kriz yönetimi gibi rekabetçi alanlarda parlar. Ekip lideri olarak belirsizlikte bile yol açar, risk almaktan çekinmez ve motivasyonuyla çevresini de ateşler. Finans konusunda cesurdur; hızlı kazanmayı sever, aynı hızda harcama eğilimindedir. Bütçe disiplini ve uzun vadeli yatırım alışkanlığı, mali enerjisini kalıcı refaha çevirmenin anahtarıdır. Bir işi bitirme becerisini geliştirdiğinde, başlattığı her proje onun en güçlü referansı olur. Ekip arkadaşları onun enerjisinden güç alır; Koç'un yanında çalışan insanlar hızlanır ve risk almaya cesaret eder.",
    strengths:
      "En parlak nitelikleri cesaret, kararlılık, liderlik ve bitmek bilmeyen yaşam enerjisidir; belirsizlik içinde bile ilk adımı atan kişidir. Gölge tarafında sabırsızlık, fevrilik ve tahammülsüzlük bulunur: işler beklendiği gibi akmadığında sinirlenebilir, yarıda bırakma eğilimine kapılabilir. Gelişim alanı nettir — detaylara ve sürekliliğe değer vermeyi öğrenmek. Sabrı bir zafer zayıflığı değil, strateji olarak gördüğünde, ateşli başlangıçlarını tamamlanmış işlere dönüştürebilir.",
    element:
      "Ateş elementinin öncü burcu olan Koç, yönetici gezegeni Mars'ın savaşçı enerjisini taşır. Mars, ona cesaret, hızlı refleks ve rekabetçi bir ruh verir; fiziksel olarak dinamik, bağışıklık sistemi güçlü ve iyileşmesi hızlıdır. Ateşin ısısı sosyal yaşamında da hissedilir: insanları hızla ısıtır, ortamın enerjisini yükseltir. Ancak Mars'ın ateşi kontrolsüz yanabilir; dinlenme ve sakinleşme ritüelleri, bu güçlü gezegenin enerjisini israf değil, yakıt hâline getirir.",
  },
  Boğa: {
    overview:
      "Boğa, Zodyak'ın sabit toprak burcudur ve hayattaki kalıcı güzelliklerin peşinden gider. Sağlam, güvenilir ve sabırlı yapısıyla tanınır; bir kez yön belirlediğinde zorluklarla bile yola devam eder. Temel motivasyonu huzur, güvenlik ve keyif almaktır: güzel yemekler, dokunulabilir konforlar, doğayla temas onun şifa kaynaklarıdır. İnatçılığı, doğru bildiği yolda ısrar etme gücü kadar bazen değişime direnmesine de yol açar. Boğa'nın olgunlaşması, sahip olduklarını korurken yeni olana da alan açmayı öğrenmesiyle başlar; sabrı onun en uzun soluklu yatırımıdır.",
    love:
      "Aşkta Boğa, sadık, dokunmatik ve duygusal olarak derin bir partnerdir. Yavaş başlar, uzun süre test eder ama bir kez güvendiğinde ilişkiye adanır. Sevgisini sözcükten çok davranışla gösterir: yanında olmak, dokunmak, pratik yardımla ilgilenmek. Romantizm, doğa yürüyüşleri, iyi bir sofra ve kaliteli zaman Boğa'nın dilidir. Kıskançlık ve sahiplenme eğilimi gölge tarafıdır; partnerinin özgürlüğüne alan açmayı öğrendiğinde güven duygusu daha da derinleşir. İlişkisinde değişime yavaş alışır, ama bir kez bağlandığında kopması en zor burçlardandır.",
    career:
      "İş hayatında Boğa, sabırlı inşa edicidir: finans, bankacılık, tarım, gastronomi, tasarım, gayrimenkul ve uzun vadeli yatırıma dayalı mesleklerde başarılıdır. Detaylara ve kaliteye verdiği önem onu güvenilir bir çalışan ve iş ortağı yapar. Parayı iyi yönetir, biriktirir; lüksü sever ama israftan hoşlanmaz. Rutin işleri ciddiyetle yapar, hızdan çok süreklilik ve sonuç odaklıdır. Kariyerindeki risk, fazla rahatlayıp konfor alanında sabitlenmek olabilir; yeni bir beceri veya rol denemesi, durgunlaşan enerjisini yeniden harekete geçirir.",
    strengths:
      "En güçlü yanları güvenilirlik, sabır, pratik zekâ ve estetik algıdır; verdiği sözü tutar, kriz anında çapa görevi görür. Gölge tarafında inatçılık, tembellik ve sahiplenici davranışlar yer alır: değişime direnmek, güvensizlikte kontrol takıntısına dönüşebilir. Gelişim alanı esnekliktir — her şeyin senin planın gibi gitmek zorunda olmadığını kabul etmek. Değişime küçük adımlarla izin verdiğinde, sağlamlığın direnç değil, bir zenginlik olduğu ortaya çıkar. Boğa'nın sabrı, en çok da başkalarının acele ettiği anlarda etrafına güven verir; o sakinleştikçe etrafı da sakinleşir.",
    element:
      "Toprak elementinin sabit burcu Boğa, yönetici gezegeni Venüs'ün zarif enerjisini taşır. Venüs ona duyusal zevk, estetik bakış ve uyum yeteneği verir; sanat, doğa ve konfor onun için birer lüks değil, ihtiyaçtır. Toprak elementi onu ayakları yere basan, gerçekçi ve üretken kılar: fikirden çok somut sonuç sever. Venüs'ün konfor arzusu, tembelliğe kaydığında toprağın verimliliği azalır; düzenli hareket ve yeni deneyimler, bu bereketli toprağı canlı tutar. Toprağın sabitliği, uzun vadeli işlerde ve yıllanacak dostluklarda onu en güvenilir ortak yapar; Boğa bir kez yol arkadaşı seçtiğinde, o yolu sonuna kadar yürür.",
  },
  İkizler: {
    overview:
      "İkizler, Zodyak'ın meraklı iletişimcisidir; zihni sürekli çalışır, öğrenme ve paylaşma ihtiyacı hiç dinmez. Hava elementinin değişken burcu olarak fikirden fikre, meraktan pratiğe kolayca geçebilir. Hayatın her katmanıyla ilgilenir — insanlar, haberler, teknoloji, dil, hikâyeler — çünkü onun için dünyanın en heyecanlı malzemesi bilgidir. Sosyal becerisi yüksektir, ortama hızla uyum sağlar, dili ve esprisiyle dikkat çeker. Dağınıklık ve yüzeysellik gölgesidir; derinleşmeyi öğrendiğinde, zekâsı bir araç olmaktan çıkıp gerçek bir rehberliğe dönüşür. Bir konuda derinleştiğinde, yüzeysel merakın ötesine geçip ustalık düzeyine ulaşabilir.",
    love:
      "Aşkta İkizler, önce zihinsel bağ kuran bir sevgilidir: iyi sohbet, zekâ ve mizah onun kapısını açar. İletişim dili çok güçlüdür; sevdiğini bilgi, fikir ve gülümsemeyle besler. İlişkide rutinden çabuk sıkılır, sürpriz ve yeniliğe ihtiyaç duyar. Partneriyle arkadaş gibi konuşabilen, her konuyu paylaşabilen bir bağ kurmak ister. Kararsızlık ve iki farklı şey söyleme eğilimi gölgesidir; ne istediğini netleştirdiğinde sadık, eğlenceli ve zeki bir partner olur. İlişkide kendine ait bir alan da ister — nefes alabildiği yerde daha çok kalır.",
    career:
      "İş hayatında İkizler, iletişim ve bilgi ustasıdır: gazetecilik, pazarlama, satış, yazılım, eğitim, çeviri, sosyal medya ve müşteri ilişkileri gibi alanlarda parlar. Hızlı öğrenir, aynı işte uzmanlaşmadan yeni bir alana geçmek isteyebilir; bu çok yönlülük onu ekiplerin bağlayıcı kişisi yapar. Kelime ve ikna yeteneği kazandırır. Finansal olarak hızlı kazanıp hızlı harcama eğilimindedir; birikimi otomatikleştirmek (yatırım talimatı, birikim hesabı) disiplinini dengeler. Birden çok projeyi aynı anda yürütebilir; önceliklendirme, enerjisini dağıtmadan kullanmasını sağlar. Sunum, müzakere ve yazı gibi alanlarda fark yaratır; karmaşık bir konuyu tek cümlede anlatmak onun doğal yeteneğidir.",
    strengths:
      "En parlak nitelikleri zekâ, çeviklik, iletişim gücü ve uyum yeteneğidir; karmaşık konuları sadeleştirebilir, insanları bir araya getirebilir. Gölge tarafında yüzeysellik, dağılma ve kararsızlık bulunur: aynı anda çok şeye başlayıp hiçbirini bitirmemek. Gelişim alanı derinliktir — bir konuda gerçekten uzmanlaşmak. Sığ suda çok hızlı, derin suda daha yavaş olduğunu fark ettiğinde, hızını bilgiyle birleştiren bir ustaya dönüşür.",
    element:
      "Hava elementinin değişken burcu İkizler, yönetici gezegeni Merkür'ün zihinsel hızını taşır. Merkür, ona analitik düşünme, dil becerisi ve hızlı öğrenme yeteneği verir; sinir sistemi hızlı çalışır, zihni hiç durmaz. Hava elementi onu sosyal, nesnel ve objektif kılar: fikir alışverişinde, yazıda ve öğretide doğaldır. Merkür'ün dağınık enerjisi, zihni dinlendirmeden yorabilir; düzenli not alma ve tek işe odaklanma pratikleri, bu güçlü zihni sakinleştirir.",
  },
  Yengeç: {
    overview:
      "Yengeç, Zodyak'ın koruyucu su burcudur ve duyguların derinliğini en iyi okuyan burçtur. Güvenlik duygusu onun pusulasıdır: ev, aile, kökler ve sevdikleri hayatının merkezindedir. Şefkatli, empatik ve sezgisel yapısıyla insanlara sıcak bir liman açar. Ancak duyguları yoğun yaşar; geri çekildiğinde kabuğuna saklanır ve yüzeyde soğuk görünebilir. Anılar ve geçmiş onun için değerlidir, bazen de yük. Olgunlaşması, korurken büyümeyi, duygusallığından güç alıp zayıflık gibi görmemeyi öğrenmesiyle tamamlanır. Ailesine ve sevdiklerine karşı derin bir sadakat taşır; onlar için kendinden vazgeçmeye hazırdır, ama kendi ihtiyaçlarını da fark etmeyi öğrenir. Geçmişe bağlılığı, ona kök duygusu verir; nereden geldiğini bilen biri, nereye gideceğini de daha sağlam seçer.",
    love:
      "Aşkta Yengeç, besleyen ve koruyan bir partnerdir. Sevdiğine şefkatini her gün gösterir: yemek, hatırlatma, kucağı. İlişkide duygusal derinlik ve güven arar; yüzeysel flörtten çok kalıcı bağ ister. Sezgileri partnerinin ruh halini ondan önce fark eder. Ev ve aile kurma isteği güçlüdür. Gölgesinde kaygı, kırgınlık ve pasif agresiflik bulunur; kırıldığında söylemeyip içine atabilir. Duygularını net ifade etmeyi öğrendiğinde, ilişkisi hayatının en güvenli limanına dönüşür. Yengeç'in sevgisi hatırlatmalar, küçük iyilikler ve yanında olmakla konuşur; sevdiği insan bunu hissettiğinde, söze gerek kalmaz.",
    career:
      "İş hayatında Yengeç, insan merkezli ve koruyucu yaklaşımdır: sağlık, eğitim, danışmanlık, gıda, emlak, çocuk ve aile alanları, gıda üretimi ve turizm gibi sektörlerde başarılıdır. Ekip içinde motivatör değil, dinleyici ve destekleyicidir; çalışanların moralini yükseltir. İşine duygusal olarak bağlanır, güvenilir ve titizdir. Finansal olarak birikimci ve temkinlidir; riskli yatırımlardan kaçınır, somut ve güvende tuttuğu araçları sever. Duygusal dalgalanmaların iş kararlarına karışmaması, profesyonel sınırlarını güçlendirir. Ekipte psikolojik güvenlik yaratır; insanlar onun yanında kendini güvende ve anlaşılır hisseder.",
    strengths:
      "En güçlü yanları empati, sadakat, sezgi ve koruyuculuktur; kriz anlarında sakinliğiyle etrafına güven verir. Gölge tarafında aşırı duygusallık, alınganlık ve geçmişe tutunmak bulunur: kırıldığını unutamaz, aynı yarayı tekrar açabilir. Gelişim alanı bırakmayı öğrenmektir. Güçlü sezgilerini kaygıyla karıştırmadığında, iç sesi onun en doğru pusulasıdır.",
    element:
      "Su elementinin öncü burcu Yengeç, yönetici gezegeni Ay'ın gelgit enerjisini taşır. Ay, ona değişken ruh halleri, güçlü sezgi ve annelik içgüdüsü verir; duyguları deniz gibi yükselir ve alçalır. Su elementi onu şefkatli, alıcı ve sezgisel kılar: insan hislerini sözcüklerden önce algılar. Ay'ın evi yönetmesi, evi ve aileyi yaşam merkezine koyar. Duygusal dalgaları tanımak ve sakinleşmek için ritüel kurmak, suyunu dalgalandıran değil besleyen bir güç hâline getirir.",
  },
  Aslan: {
    overview:
      "Aslan, Zodyak'ın kraliyet burcudur; hayatı sahne gibi görür ve kendini açıkça ifade etmek ister. Güneş'in etkisiyle doğuştan parlak, cömert ve sıcak bir çekim alanı taşır. Liderlik, yaratıcılık ve gösteriş onun doğal dilidir; ne yaparsa yapsın fark edilmek ve takdir edilmek motivasyonunu besler. Kalbi büyüktür, dostlarına ve sevdiklerine cömertçe dağıtır. Gölgesinde gurur, kibir ve onay bağımlılığı bulunur; takdir beklentisini kendi içsel değerine çevirdiğinde, gerçek gücünü ve sıcaklığı keşfeder. En parlak anları, kalabalık karşısında ya da sevdikleriyle birlikteyken yaşanır; paylaştıkça çoğalan bir enerjisi vardır.",
    love:
      "Aşkta Aslan, romantik, cömert ve gösterişli bir partnerdir. Sevgisini büyük jestlerle, sözlerle ve sahiplenmeyle yaşar; sevdiğini dünyaya ilan etmekten çekinmez. İlişkide hayranlık ister — partnerinin ona bakışı, onun en büyük yakıtıdır. Sadıktır ve koruyucudur. Gölgesinde kıskançlık ve egonun öne çıkması vardır; eleştiriyi kişisel algılayabilir. Partnerini kendisi gibi parlatmayı öğrendiğinde, ilişkisi iki yıldızın birlikte parladığı bir sahneye dönüşür. Romantizmi cömert ve hatırla doludur; sevdiğinin özel günlerini, ilklerini ve küçük zaferlerini hep hatırlar.",
    career:
      "İş hayatında Aslan, yaratıcı liderdir: yöneticilik, sanat, eğlence, medya, eğitim, sahne ve marka yönetimi gibi dikkat gerektiren alanlarda parlar. Ekibe ilham verir, vizyon çizmeyi ve kalabalıkları yönetmeyi sever. İşini prestijle yapar, vasat işlerden hoşlanmaz. Finansal olarak cömerttir; harcamayı ve paylaşmayı sever, bütçe disiplini zaman zaman zorlanır. Günlük işleri değil, büyük resmi sever; yetki ve takdir alanlarında en verimli hâlindedir. Vasat bir işi büyük bir işe dönüştürme gücü vardır; çünkü isterken kendini de katar.",
    strengths:
      "En parlak nitelikleri yaratıcılık, cömertlik, liderlik ve sarsılmaz öz güvenidir; zor günlerde bile umut saçar. Gölge tarafında kibir, Drama eğilimi ve onay arayışıdır: takdir gelmediğinde motivasyonu düşebilir. Gelişim alanı alçakgönüllülük ve içsel takdir. Kendi ışığını başkalarının onayından bağımsız yaktığında, liderlik gerçekten ilham verici hâle gelir. Kendini ve sevdiklerini değerli hissettirme becerisi, onun en doğal hediyelerinden biridir.",
    element:
      "Ateş elementinin sabit burcu Aslan, yönetici gezegeni Güneş'in ışığıyla aydınlanır. Güneş, ona yaşam enerjisi, otorite ve doğal karizma verir; ışığını gizlemek yerine paylaşmak için doğar. Ateşin sıcaklığı cömertliğine, tutkusuna ve yaratıcılığına yansır. Güneş'in merkezî konumu, merkezde olma ihtiyacını da besler; ışığını sergilemek için değil, ilham vermek için kullandığında etkisi en yükseğe çıkar. Güneş'in merkezî gücü, ona yaşlandıkça da kaybetmediği bir canlılık ve sahne hakimiyeti bahşeder; sahne onun doğal evidir.",
  },
  Başak: {
    overview:
      "Başak, Zodyak'ın analitik ve hizmet odaklı toprak burcudur; dünyayı daha iyi, daha düzenli ve daha verimli hâle getirmek ister. Detaylara hakim, pratik ve çalışkandır; gözünden kusur kaçmaz. Mükemmelliğe yakın bir standartla çalışır, bu da hem kalitesini hem de kendine yükünü artırır. Bilgiyi toplamayı, sınıflandırmayı ve uygulamayı sever. Gölgesinde eleştirel olma, kaygı ve kendini fazla zorlama bulunur; kusursuzluk yerine iyiyi hedeflediğinde, detaylar onun için yük değil bir ustalık aracı olur. Çalışma disiplini, onu yalnız kendi alanında değil, ekibinin de güvenilir çıpası yapar.",
    love:
      "Aşkta Başak, sessiz ama derin sevgi gösteren bir partnerdir. Duygularını büyük sözlerle değil, hizmetle ve özenle ifade eder: sevdiğinin hayatını kolaylaştırmak, pratik yardımda bulunmak onun aşk dilidir. Güvenmek için zaman ister, seçicidir. İlişkide dürüstlük ve zihinsel uyum arar; abartılı romantizmden çok gerçekçilik ister. Gölgesinde eleştirel olma ve duygularını erteleme vardır: partnerini sürekli iyileştirme çabası yorabilir. Sevgiyi kabul etmeyi ve her detayı düzeltmeye çalışmadan, olduğu gibi de sevmeyi öğrendiğinde, sakin ve güvenilir bir yoldaş olur. Sadakati ve pratik özeni, yıllar geçtikçe derinleşen bir bağ kurmasını sağlar.",
    career:
      "İş hayatında Başak, düzen ve kalite uzmanıdır: analiz, muhasebe, yazılım kalite güvence, editörlük, sağlık, araştırmacılık ve operasyon yönetimi gibi titizlik isteyen alanlarda başarılıdır. İşini dakik ve doğru yapar, ekiplerin hata yakalayıcısıdır. Öğrenmeye açıktır, kendini sürekli geliştirir. Finansal olarak tutumludur, gereksiz harcamadan hoşlanmaz; birikim ve planlama konusunda güçlüdür. Mükemmellik beklentisi onu yavaşlatabilir; işleri 'yeterince iyi' diye teslim etmeyi öğrenmek, verimliliğini katlar. Eleştirisini yapıcı kullandığında, ekiplerinin kalitesini yükselten en değerli göz olur.",
    strengths:
      "En güçlü yanları analitik zekâ, çalışkanlık, güvenilirlik ve pratik yardımseverliktir; karmaşık sorunları parçalayıp çözüme kavuşturur. Gölge tarafında aşırı eleştirellik, kaygı ve kendini yeterince görmeme bulunur. Gelişim alanı kendine şefkat: mükemmel olmayana da yer açmak. Kendine başkalarına davrandığı kadar yumuşak davrandığında, detaylar yükünden ustalığına geçer. Günlük küçük alışkanlıklar onun en güçlü dönüşüm alanıdır; bir ritüel kurduğunda yıllarca sürdürür.",
    element:
      "Toprak elementinin değişken burcu Başak, yönetici gezegeni Merkür'ün zihinsel keskinliğini taşır. Merkür, ona analiz, sınıflandırma ve pratik çözüm becerisi verir; zihni sürekli iyileştirme arar. Toprak elementi bu zihinsel gücü somut işe döker: fikir değil, uygulanan çözüm sever. Merkür'ün hızı, zihni durdurmakta zorlanmasına yol açabilir; bedensel hareket, doğa ve düzenli dinlenme, analitik zihnini dengeler. Küçük ve ölçülebilir hedefler koyduğunda, zihinsel keskinliğini korurken kendine de iyi bakar.",
  },
  Terazi: {
    overview:
      "Terazi, Zodyak'ın denge ve adalet arayan hava burcudur; güzelliği, uyumu ve adil olanı hayatının merkezine koyar. İlişkilerde ustaldır: insanları anlamak, karşının yerine bakmak ve ortak zemin bulmak onun doğal yeteneğidir. Estetik algısı güçlüdür; sanat, tasarım ve zarafet onun dilidir. Karar vermekte zorlanabilir, çünkü her iki tarafın da hakkını görmek ister. Olgunlaşması, dengeyi korurken kendi sınırını da koymayı; uyum ararken kendinden vazgeçmemeyi öğrenmesiyle tamamlanır. İnsanları bir araya getirme ve gerilimi yumuşatma yeteneği, onu hem sosyal yaşamında hem işinde aranan biri yapar.",
    love:
      "Aşkta Terazi, romantik, zarif ve uyumlu bir partnerdir. İlişkide denge, karşılıklı saygı ve adalet arar; kavga yerine dialog seçer. Partneriyle estetik ve zihinsel paylaşımı sever: birlikte güzel vakit geçirmek onun için aşkın kendisidir. Flört yeteneği güçlüdür, ilk adımı zarifçe atar. Gölgesinde uyum için fazlasıyla taviz verme ve kararsızlık bulunur: ihtiyaçlarını söylemediğinde içten içe birikebilir. 'Hayır' diyebilmeyi öğrendiğinde, ilişkisi hem uyumlu hem dürüst olur. Zarafeti tartışmayı değil, dialogu açar; kırıcı olmadan sınır koymak onun ustalık alanıdır.",
    career:
      "İş hayatında Terazi, diplomatik ve estetik çözümcüdür: hukuk, insan kaynakları, halkla ilişkiler, tasarım, mimarlık, sanat yönetimi ve müşteri ilişkileri gibi insan ve denge gerektiren alanlarda başarılıdır. Ortaklıklarda güçlüdür, ekipler arası köprü olur. Görsel zevki ve adalet duygusu onu güvenilir bir danışman yapar. Finansal olarak dengeli harcamayı sever, güzel olanı alır ama bütçesini de zorlamaz. Karar gecikmeleri en büyük riskidir; küçük kararlarda hızlanma alışkanlığı, büyük fırsatları kaçırmasını engeller.",
    strengths:
      "En parlak nitelikleri adalet duygusu, diplomasi, estetik ve sosyal zekâdır; çatışmaları yumuşatır, ortak zemin bulur. Gölge tarafında kararsızlık, uyum için kendini kaybetme ve yüzeyde kalma bulunur. Gelişim alanı net sınırlar: denge, her şeyi eşitlemek değil, doğru ağırlığı koymaktır. Kendi kırmızı çizgilerini bildiğinde, uyum ustası olmak zayıflık değil bir güç olur. Adalet duygusu, onu yalnız kendi hayatında değil, başkalarının hak arayışında da güvenilir bir müttefik yapar.",
    element:
      "Hava elementinin öncü burcu Terazi, yönetici gezegeni Venüs'ün sevgi ve denge enerjisini taşır. Venüs ona zarafeti, sanatsal algıyı ve ilişki kurma becerisini verir; güzelliğe ve uyuma doğal çekimi vardır. Hava elementi, bu duygusallığı objektif bir adalet duygusuyla dengeler: Terazi hem sever hem de tartar. Venüs'ün uyum arayışı, kendi isteklerini geri plana atmasına yol açabilir; kalbinin sesini de bir ölçü olarak eklediğinde denge tamamlanır.",
  },
  Akrep: {
    overview:
      "Akrep, Zodyak'ın en derin ve dönüştürücü su burcudur; yüzeyin altındaki gerçeği görmeyi ve her şeyi kökten yenilemeyi ister. Yoğun, gizemli ve kararlıdır; bir hedefe kilitlendiğinde durdurulması zordur. Bağlanma ve sadakat onun için ciddi bir meseledir, yüzeysel olanı reddeder. Krizleri ve dönüşümleri yönetme gücü yüksektir; en zor anlarda bile sakin kalır. Gölgesinde kontrol takıntısı, şüphe ve intikam hissi bulunur; güvenmeyi öğrendiğinde, yoğunluğu korkutucu değil büyüleyici bir güvene dönüşür. Kriz anında soğukkanlılığıyla bilinir; ne yaşanırsa yaşansın panik yapmadan çözüm arar ve etrafına da bu sakinliği bulaştırır.",
    love:
      "Aşkta Akrep, tutkulu ve tam bağlı bir partnerdir; yarı ölçü onun lügatında yoktur. Sevdiğinde derinden sever, sadakat ve gizlilik ister. İlişkide duygusal derinlik, fiziksel çekim ve psikolojik bağ arar; oyunları ve samimiyetsizliği hemen fark eder. Kontrol ve kıskançlık gölgesi, güven sarsıldığında ortaya çıkar. Partneriyle güç savaşına girmemeyi ve zayıflığını paylaşmayı öğrendiğinde, hayatı boyunca aradığı amansız sadakatli bağı kurar. Ayrılığı da en zor bırakan burçtur; ama bıraktığında tamamen bırakır.",
    career:
      "İş hayatında Akrep, stratejik ve dönüştürücüdür: araştırma, psikoloji, finans, dedektiflik, cerrahi, kriz yönetimi, mühendislik ve gizlilik gerektiren alanlarda başarılıdır. Sorunun altına iner, tabuları konuşur, krizleri fırsata çevirir. Güç ve kontrol gerektiren rollerde parlar, strateji kurmakta ustadır. Finansal olarak sezgileri güçlüdür; riskli ama hesaplı yatırımları sever, kaynaklarını gizli tutar. Güvenmediği ortamlarda çalışmak zorlaşır; şeffaf ilişkiler ve net yetkiler, gücünü dağıtmadan kullanmasını sağlar. Sadakati ve gizliliği, onu en zorlu iş ortaklıklarında bile güvenilir bir sırdaş yapar.",
    strengths:
      "En güçlü yanları kararlılık, sezgi, dayanıklılık ve dönüştürme gücüdür; kriz anında en sağlam limandır. Gölge tarafında şüphe, kontrol ihtiyacı ve öfke bulunur: her şeyi yönetmeye çalıştığında yorulur ve yalnızlaşır. Gelişim alanı teslimiyet: kontrolün her yerde olmadığını kabul etmek. Güvenin kırılgan bir şey olduğunu bilerek kurduğunda, derinliği bir korku değil, bir güç kaynağı olur. Güvenmeyi öğrendiğinde, insanları yüzeyden değil özden tanıma yeteneği ona eşsiz bir içgörü kazandırır.",
    element:
      "Su elementinin sabit burcu Akrep, yönetici gezegeni Plüton'un dönüştürücü enerjisini taşır (klasik atıf Mars da etkilidir). Plüton, ona yeniden doğuş yeteneği verir: her çöküşten daha güçlü çıkmasını sağlar. Su elementi, duygularını derin ve gizli yaşamasını sağlar; yüzeyde sakin, altta yoğun bir okyanustur. Plüton'un yoğunlaşması, kontrol ve gizlilik ihtiyacını besler; duygularını güvendiği biriyle paylaştığında, bu güç dönüştürücü bir şifaya dönüşür.",
  },
  Yay: {
    overview:
      "Yay, Zodyak'ın maceracı ve felsefi ateş burcudur; ufuk çizgisinin ötesini merak eder, bilgiyi ve deneyimi sınırsızca arar. İyimserliği ve mizahı onun imzasıdır; zorluklar bile onun gözünde yeni bir hikâye başlangıcıdır. Özgürlüğe ve genişlemeye ihtiyaç duyar: seyahat, eğitim, felsefe, inanç sistemleri onun besin kaynakları. Doğrudan ve açık sözlüdür, yalan söylemekten hoşlanmaz. Gölgesinde savurganlık, sözünü tutmama ve aşırı iyimserlik bulunur; büyük hayallerini küçük adımlarla inşa etmeyi öğrendiğinde, gerçek bir keşif rehberine dönüşür. Öğrenmeyi bir hayat tarzı olarak görür; yaşlandıkça merakını kaybetmez, her yeni deneyim ona yeni bir bakış açısı kazandırır.",
    love:
      "Aşkta Yay, neşeli, özgür ve iyimser bir partnerdir. İlişkide arkadaşlık ve macera arar: birlikte yolculuk yapmak, yeni şeyler denemek, gülmek aşkının temelidir. Dürüst ve doğrudandır; oyun oynamaz. Bağlanma korkusu ve özgürlük ihtiyacı gölgesidir; baskı hissettiğinde uzaklaşabilir. Partneriyle ortak bir macera paylaştığında sadık ve cömert bir yoldaş olur. Ciddi konuşmaları ve duygusal derinliği de ilişkisine eklediğinde, yüzeydeki neşenin altında güçlü bir bağ kurar. Ortak seyahatler ve yeni deneyimler, onun aşkını canlı tutan en önemli ritüellerdir; birlikte keşfetmedikçe ilişki durgunlaşır.",
    career:
      "İş hayatında Yay, vizyoner keşifçidir: seyahat, yayıncılık, akademi, spor, eğitim, turizm ve uluslararası işler gibi ufuk açan alanlarda başarılıdır. Motivasyonu yüksek, cesur ve iyimserdir; ekibe umut aşılar. Yeni pazarlara, yeni fikirlere ilk giden kişidir. Finansal olarak cömert ve savorgandır; kazanmayı da harcamayı da sever. Düzenli tasarruf ve hedefli bütçe, büyük hayallerini finanse etmesini kolaylaştırır. Aynı anda tek bir büyük hedefe odaklanmak, gücünü toplamasını sağlar. Motivasyonu yalnız kendini değil, ekibini de ileri taşır; zor günlerde bile iyimserliğini koruyan bir lider profili çizer.",
    strengths:
      "En parlak nitelikleri iyimserlik, özgürlük sevgisi, mizah ve felsefi derinliktir; en karanlık günde bile yol gösterir. Gölge tarafında savurganlık, söz tutmama ve kaçış eğilimi bulunur: sorumluluktan uzaklaşmak bazen özgürlükle karıştırılır. Gelişim alanı taahhüt: bir şeye gerçekten bağlanmak. Sözünü tuttuğunda ve planını bitirdiğinde, özgürlüğü bir kaçış değil, bir fetih hâline gelir. Yaşam sevinci, onun etrafındaki insanlara da bulaşır.",
    element:
      "Ateş elementinin değişken burcu Yay, yönetici gezegeni Jüpiter'in genişletici enerjisini taşır. Jüpiter, ona şans, iyimserlik ve büyüme açlığı verir; hayatın büyük sorularıyla ilgilenir, ufukları genişletir. Ateşin canlılığı sosyal enerjisine ve cesaretine yansır. Jüpiter'in 'daha fazlası' dürtüsü, savurganlığa ve aşırıya kaçmaya yol açabilir; amaç ve ölçülülük, bu bereketli gezegenin hediyelerini kalıcı kılar.",
  },
  Oğlak: {
    overview:
      "Oğlak, Zodyak'ın disiplinli ve hedef odaklı toprak burcudur; hayatı bir başarı mimarisi gibi kurar. Ciddi, sorumlu ve sabırlıdır; kısa yoldan değil, sağlam temelden ilerler. Statü, saygı ve somut sonuçlar onun için önemlidir; emeğiyle bir şeyler inşa etmek en büyük haz verir. Erken yaşta olgunlaşabilir, sorumluluk almak onun doğal konumudur. Gölgesinde aşırı çalışma, duygusal mesafe ve başarısızlık korkusu bulunur; hayatı sadece hedeflerden ibaret olmadığını fark ettiğinde, sıkı disiplini sıcak bir bilgelikle dengelenir. Erken yaşlarda edindiği sorumluluk bilinci, onu hem iş hem özel hayatta güvenilir bir planlayıcı yapar.",
    love:
      "Aşkta Oğlak, ciddi, sadık ve güvenilir bir partnerdir; ilişkiye de kariyeri gibi özenle yaklaşır. Çekingen başlar, duygularını yavaş açar ama bağlandığında son derece sadıktır. Güven, saygı ve ortak hedefler arar; abartılı romantizmden çok gerçek bir yaşam planı ister. Zaman ayırma konusunda öğüt veren, pratik sevgi dili vardır. Gölgesinde duygusal mesafe ve işi önceliklendirme vardır: duygularını ifade etmeyi öğrendiğinde, beklemeye değer en sağlam eşlerden biri olur. Sadakati sözünde değil, her gün verdiği küçük kararlarda kendini gösterir; yanında olduğu insan bunu zamanla fark eder.",
    career:
      "İş hayatında Oğlak, kurumsal yükselişin ustasıdır: yöneticilik, finans, hukuk, mühendislik, inşaat, kamu yönetimi ve strateji gibi disiplin gerektiren alanlarda zirveye çıkar. Hedef koyar, planlar, sabırla uygular. Çalışma etiği güçlüdür, güvenilir ve sorumludur. Finansal olarak en disiplinli burçlardandır: birikir, yatırım yapar, uzun vadeli düşünür. İş ile özel hayatı dengeleme riski en büyük sınavıdır; takvimine sevdikleri için de zaman ayırdığında, başarı yalnız bir zirve değil, paylaşılan bir zafer olur.",
    strengths:
      "En güçlü yanları disiplin, sabır, sorumluluk ve stratejik düşüncedir; uzun vadeli hedefleri adım adım gerçekleştirir. Gölge tarafında aşırı ciddiyet, duygusal katılaşma ve başarısızlık korkusu bulunur: hata yapmamak için risk almakta gecikebilir. Gelişim alanı esneklik ve şefkat: planın da değişebileceğini kabul etmek. Mükemmel planı beklerken gelen fırsatları da görebildiğinde, disiplini bir kale değil, bir köprü olur.",
    element:
      "Toprak elementinin öncü burcu Oğlak, yönetici gezegeni Satürn'ün sınırlama ve olgunlaştırma enerjisini taşır. Satürn, ona sorumluluk, sabır ve zamanla olgunlaşma dersleri verir; gençken ağır gelen bu yük, yaşla birlikte ustalığa dönüşür. Toprak elementi, hayalleri somut ve kalıcı yapıya döker. Satürn'ün katı sesi, kendiyle acımasız konuşmaya yol açabilir; iç sesini bir öğretmen kadar sert değil, bir koç kadar destekleyici yaptığında, bu gezegenin disiplini yıldıza dönüşür.",
  },
  Kova: {
    overview:
      "Kova, Zodyak'ın vizyoner ve bağımsız hava burcudur; kuralları sorgular, geleceği bugünden yaşar. Özgün düşüncesi ve toplumsal duyarlılığıyla kalabalıklardan ayrılır; ait olduğu yeri kendi seçer. İnsanlığı ve ilerlemeyi önemser, gruplar içinde ama gruba bağlı olmadan durur. Değişime ve yeniliğe doğuştan açıktır; dünün kalıplarına değil, yarının ihtimallerine bakar. Gölgesinde duygusal mesafe, inat ve kopukluk bulunur: hislerini göz ardı etmeden özgürlüğünü koruduğunda, vizyonu gerçekten dönüştürücü olur. Grup içinde ama gruba bağlı olmadan durmak, ona hem bağımsızlık hem de geniş bir perspektif kazandırır.",
    love:
      "Aşkta Kova, önce arkadaş olan, sonra aşık olan bir partnerdir; zihinsel bağ ve ortak idealler onun için vazgeçilmezdir. İlişkide özgürlük ve alan ister; bağlanma ile bağımsızlığı aynı anda yaşar. Sürpriz, ilginç ve bağımsız insanları sever, rutin ilişkilerden sıkılır. Duygularını ifade etmekte gecikebilir, mesafeli görünebilir. Partnerini bir birey olarak özgür bıraktığında ve kendi duygularına da yer açtığında, nadir bulunan birer hem sevgili hem yoldaş olurlar. Sürpriz yapmayı ve rutini kırmayı sever; partneri için hazırladığı özgün jestler, aşkını en canlı ifade biçimidir.",
    career:
      "İş hayatında Kova, yenilikçi ve teknolojik düşünürdür: yazılım, bilim, AR-GE, sosyal girişimcilik, uzay-teknoloji, icat ve sivil toplum gibi geleceğe dönek alanlarda başarılıdır. Sistemleri yeniden kurma cesareti vardır, sıradışı çözümler üretir. Otoriteye bağlı çalışmak yerine proje bazlı ve özerk ortamları sever. Finansal olarak yaratıcıdır; geleneksel birikim yerine yenilikçi araçlara ilgi duyar. Ekiple uyum, vizyonunun hayata geçmesini hızlandırır: tuhaflığı bir avantaj, mesafesi bir liderlik stiline dönüştürebilir.",
    strengths:
      "En parlak nitelikleri özgünlük, vizyon, insancıllık ve objektifliktir; kalabalıkların göremediği çözümleri görür. Gölge tarafında duygusal kopukluk, inat ve status quo'yu reddetme takıntısı bulunur: değişim için değişmek. Gelişim alanı bağ: insani duyguları sistemin bir parçası olarak kabul etmek. Kalbiyle zihnini aynı masaya oturttuğunda, vizyonu yalnız bir fikir değil, bir hareket olur. Geleceğe dair öngörüleri, zamanla doğru çıkan ve çevresindekilere yol gösteren bir perspektife dönüşür.",
    element:
      "Hava elementinin sabit burcu Kova, yönetici gezegeni Uranüs'ün ani ve yenilikçi enerjisini taşır (klasik atıf Satürn de etkilidir). Uranüs, ona sürpriz değişim, özgünlük ve aykırı düşünceler verir; beklenmedik sıçramalarla ilerler. Hava elementi, düşüncelerini toplumsal faydaya yöneltir: Kova yalnız düşünmez, insanlık için düşünür. Uranüs'ün ani dalgaları, öngörülemezlik ve iç huzursuzluk yaratabilir; düzenli rutinler ve güçlü bağlar, bu elektriksel enerjiyi istikrarlı bir ışığa çevirir. Uranüs'ün ani dalgaları, beklenmedik dönüşümleri ve zaman ötesi fikirleri de beraberinde getirir.",
  },
  Balık: {
    overview:
      "Balık, Zodyak'ın son burcu ve en sezgisel su burcudur; sınırların, rüyaların ve şefkatin burcudur. Empati yeteneği o kadar yüksektir ki başkalarının duygularını kendi gibi yaşar. Hayal gücü, sanatsal duyarlılık ve ruhsal derinlik onun doğal alanı vardır; gerçeklikle bağını bazen koparır, kaçış yolları arar. İncelikli ve fedakârdır. Gölgesinde kurban rolü, dağınıklık ve bağımlılık eğilimi bulunur; sınırlarını çizmeyi ve hayallerini somut adımlarla takip etmeyi öğrendiğinde, sezgisi dünyanın en güçlü pusulasına dönüşür. Rüyaları ve ilk sezgileri genellikle isabetlidir; onları küçümsememek, hayatındaki en doğru kararlardan biri olabilir.",
    love:
      "Aşkta Balık, koşulsuz seven, romantik ve fedakâr bir partnerdir; adeta ruhu eşiyle bağlantılı ister. Sevgide idealize etme eğilimi yüksektir: gördüğü potansiyeli sever. Şefkati ve affediciliği güçlüdür, kalbi büyüktür. İlişkide duygusal derinlik, maneviyat ve sanatsal paylaşım arar. Gölgesinde sınırları belirsiz olmak ve kendini kaybetmek vardır; partnerinin ve kendinin ihtiyaçlarını netleştirdiğinde, en derin ve en şifalı ilişkileri kuran burç olur. Sevdiğinin yanında duygusal olarak güvende hissettiğinde, sadakati ve fedakârlığı sınır tanımaz hâle gelir.",
    career:
      "İş hayatında Balık, sezgisel ve yaratıcıdır: sanat, müzik, tasarım, film, şifa alanları, bakım hizmetleri, manevi danışmanlık ve hayır kurumları gibi duyarlılık gerektiren alanlarda parlar. Empatiyle insanları anlar, atmosferi hisseder, yaratıcı çözümler üretir. Sınır ve detay yönetimi zayıf olabilir; net görev tanımları ve düzenli sistemler onu güçlendirir. Finansal olarak cömert ve bazen dağınıktır; otomatik birikim ve net bütçe, hassas enerjisini korur. İlhamla çalıştığında sıra dışı eserler üretir. Yaratıcı projelerde ve insan odaklı işlerde, detaycı değil duygusal zekâsıyla fark yaratır.",
    strengths:
      "En parlak nitelikleri empati, şefkat, yaratıcılık ve sezgidir; kelimelerin yetmediği yerde anlar ve şifalandırır. Gölge tarafında sınır eksikliği, kaçış ve kurban bilinci bulunur: başkalarının yükünü sırtlanıp kendini unutabilir. Gelişim alanı net sınırlar: herkese yardım etmek, kimseye yardım edememekle sonuçlanabilir. Kendi kıymetini bildiğinde, şefkati bir delilik değil, bir ustalık olur. Duygularını kendi gibi değerli gördüğünde, başkalarını şifalandırırken kendini de ihmal etmemeyi öğrenir.",
    element:
      "Su elementinin değişken burcu Balık, yönetici gezegeni Neptün'ün hayal ve birleşme enerjisini taşır. Neptün, ona sanatsal ilham, rüyalar ve sınırsız empati verir; gerçeklik ile hayalin sınırı onun için soluktur. Su elementi, duyguları sünger gibi emen bir hassasiyet verir. Neptün'ün sisli etkisi, odak ve sınır zorluğu yaratabilir; karaya çıkmak — düzenli rutin, somut hedefler ve net 'hayır'lar — bu muazzam sezgiyi hayatta tutan çapa olur.",
  },
};
